### ISSUE TITLE
登录时报错

### ISSUE THREAD

**Issue by NeoFii** [littlecodersh/ItChat#1018]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）
1.3.10
其他的内容或者问题更详细的描述都可以添加在下面：
运行
```
import itchat

itchat.auto_login(hotReload=True)

itchat.run()

```
后报错：
```
Traceback (most recent call last):
  File "E:\Pycharm\codes\itchat\1.py", line 3, in <module>
    itchat.auto_login(hotReload=True)
  File "E:\Pycharm\codes\itchat\.venv\Lib\site-packages\itchat\components\register.py", line 31, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "E:\Pycharm\codes\itchat\.venv\Lib\site-packages\itchat\components\login.py", line 53, in login
    status = self.check_login()
             ^^^^^^^^^^^^^^^^^^
  File "E:\Pycharm\codes\itchat\.venv\Lib\site-packages\itchat\components\login.py", line 137, in check_login
    if process_login_info(self, r.text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Pycharm\codes\itchat\.venv\Lib\site-packages\itchat\components\login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\Lib\xml\dom\minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\Lib\xml\dom\expatbuilder.py", line 922, in parseString
    return builder.parseString(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\Lib\xml\dom\expatbuilder.py", line 220, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4
```
请问是什么原因？

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by Johnson1103** [comment]
我也碰到同样的问题。 可能是项目停滞维护了吧。微信应该更新登录接口了

**Comment by assassinfall** [comment]
同上

**Comment by brady-wang** [comment]
同上
