### ISSUE TITLE
运行入门例子报错....'itchat' has no attribute 'msg_register'

### ISSUE THREAD

**Issue by issmile** [littlecodersh/ItChat#132]
python2 和python3都试过,报错的

```
E:\weixin\itchat>python itchat.py
Traceback (most recent call last):
  File "itchat.py", line 1, in <module>
    import itchat
  File "E:\weixin\itchat\itchat.py", line 3, in <module>
    @itchat.msg_register(itchat.content.TEXT)
AttributeError: module 'itchat' has no attribute 'msg_register'
```

```
import itchat

@itchat.msg_register(itchat.content.TEXT)
def text_reply(msg):
    itchat.send(msg['Text'], msg['FromUserName'])

itchat.auto_login()
itchat.run()
```

**Comment by tempdban** [comment]
把itchat.py 改成 test.py

**Comment by issmile** [comment]
666
