### ISSUE TITLE
报告语法错误,运行readme代码

### ISSUE THREAD

**Issue by chijiao** [littlecodersh/ItChat#136]
```
#coding=utf8
import itchat, time
from itchat.content import *

@itchat.msg_register([TEXT, MAP, CARD, NOTE, SHARING])
def text_reply(msg):
    itchat.send('%s: %s' % (msg['Type'], msg['Text']), msg['FromUserName'])

@itchat.msg_register([PICTURE, RECORDING, ATTACHMENT, VIDEO])
def download_files(msg):
    msg['Text'](msg['FileName'])
    return '@%s@%s' % ({'Picture': 'img', 'Video': 'vid'}.get(msg['Type'], 'fil'), msg['FileName'])

@itchat.msg_register(FRIENDS)
def add_friend(msg):
    itchat.add_friend(**msg['Text']) # 该操作会自动将新好友的消息录入，不需要重载通讯录
    itchat.send_msg('Nice to meet you!', msg['RecommendInfo']['UserName'])

@itchat.msg_register(TEXT, isGroupChat=True)
def text_reply(msg):
    if msg['isAt']:
        itchat.send(u'@%s\u2005I received: %s' % (msg['ActualNickName'], msg['Content']), msg['FromUserName'])

itchat.auto_login(True)
itchat.run()
```

```
Traceback (most recent call last):
  File "wx.py", line 2, in <module>
    import itchat, time
  File "/usr/lib/python2.6/site-packages/itchat/__init__.py", line 3, in <module>
    from .client import client
  File "/usr/lib/python2.6/site-packages/itchat/client.py", line 434
    cookiesList = {name:data for name,data in self.s.cookies.items()}
                               ^
SyntaxError: invalid syntax
```

**Comment by littlecodersh** [comment]
@chijiao 升级2.7吧，itchat支持2.7以上版本（-3.5）
