### ISSUE TITLE
console中如何输出群列表,直接回复群列表应该怎么弄?

### ISSUE THREAD

**Issue by issmile** [littlecodersh/ItChat#142]
第一次用itchat 我想输出群列表.报错了,不知道改怎么弄这个转码,会送给发信息的好友也不知道该怎么发,希望大神指点下,python不太熟悉,请见谅
```
#coding=utf8
import itchat, time
from itchat.content import *

@itchat.msg_register([TEXT, MAP, CARD, NOTE, SHARING])
def text_reply(msg):
    print("1111")
    qun=itchat.get_chatrooms()
    print(qun)
    itchat.send('%s: %s' % (msg['Type'], msg['Text']), msg['FromUserName'])

itchat.auto_login(True)
itchat.run()
itchat.get_chatrooms()
```

error:
E:\weixin\itchat>python test.py
Login successfully as 一二三
Start auto replying
1111
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    itchat.run()
  File "E:\Program Files (x86)\Python35-32\lib\site-packages\itchat\__init__.py", line 120, in run
    configured_reply()
  File "E:\Program Files (x86)\Python35-32\lib\site-packages\itchat\__init__.py", line 96, in configured_reply
    if replyFn: send(replyFn(msg), msg.get('FromUserName'))
  File "test.py", line 9, in text_reply
    print(qun)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f338' in position 3036: illegal multibyte sequence

**Comment by littlecodersh** [comment]
@issmile 这是基本的字符串操作，你可以参考一下[这篇文章][python-encode]。

[python-encode]: http://python.jobbole.com/85482/
