### ISSUE TITLE
注册note 邀请成员进入后,print msg 报错

### ISSUE THREAD

**Issue by issmile** [littlecodersh/ItChat#147]
代码:
```
@itchat.msg_register(NOTE)
def text_reply(msg):
    print (msg)
```
在群内邀请成员后就报错了,提示如下,不知道是不是不应该用print查看msg内容,如果不应该用print 来查看msg内容,那我应该怎么查看邀请信息的内容?

```bash
Traceback (most recent call last):
  File "E:\Python27\lib\site-packages\itchat\client.py", line 267, in maintain_loop
    msgList, contactList = self.__get_msg()
  File "E:\Python27\lib\site-packages\itchat\client.py", line 308, in __get_msg
    r = self.s.post(url, data = json.dumps(payloads), headers = headers)
  File "E:\Python27\lib\site-packages\requests\sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "E:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "E:\Python27\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
Traceback (most recent call last):
  File "test.py", line 50, in <module>
    itchat.auto_login(True)
  File "E:\Python27\lib\site-packages\itchat\__init__.py", line 121, in run
    time.sleep(.3)
```

**Comment by littlecodersh** [comment]
@issmile 看报错来说是获取消息失败，连接中断。
打印的话用repr。
```python
print(repr(msg))
```
