### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by anderson916** [littlecodersh/ItChat#154]
➜  ~ python wx.py
Getting uuid of QR code.
Downloading QR code.
```
Traceback (most recent call last):
  File "wx.py", line 24, in <module>
    itchat.auto_login(True)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/register.py", line 23, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 37, in login
    if self.get_QR(enableCmdQR=enableCmdQR, picDir=picDir):
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 88, in get_QR
    utils.print_qr(picDir)
  File "/usr/local/lib/python2.7/dist-packages/itchat/utils.py", line 71, in print_qr
    subprocess.call(['xdg-open', fileDir])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by littlecodersh** [comment]
@anderson916 当前目录下有生成二维码吗？
python有权限在本目录写入二维码吗？

**Comment by anderson916** [comment]
生成了二维码。 

<img width="403" alt="screen shot 2016-11-16 at 8 53 03 pm" src="https://cloud.githubusercontent.com/assets/195719/20348070/c3da030e-ac3e-11e6-844b-5ad1604f9b18.png">

**Comment by littlecodersh** [comment]
@anderson916 你是使用的什么程序运行该项目？
如果使用命令行是否可以打开该文件？
```bash
xdg-open QR.jpg
```

**Comment by anderson916** [comment]
```
➜  ~ ./wx.py
Getting uuid of QR code.
Downloading QR code.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at /usr/bin/run-mailcap line 528.
Error: no "view" mailcap rules found for type "image/jpeg"
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'QR.jpg'
Please scan the QR code to log in.

```

**Comment by littlecodersh** [comment]
@anderson916 你试试这个选项
```python
itchat.auto_login(enableCmdQR=True)
```

**Comment by anderson916** [comment]
可以了。谢谢。

**Comment by 19940308cai** [comment]
![image](https://user-images.githubusercontent.com/20193598/31662485-255d1a7c-b304-11e7-8e5d-87dbe7ff71cb.png)

**Comment by erictioh** [comment]
I think you have to install xdg-utils before the it can try to open it. The command line is another way.

for centos: yum install xdg-utils
