### ISSUE TITLE
异常 Connection aborted

### ISSUE THREAD

**Issue by qing6010** [littlecodersh/ItChat#163]
挂了之后每隔一段时间(几个小时)就会出现如下错误并退出。按经验是只有发送消息的时候才出错，错误来自itchat.send，若没收到消息不会报错。检查发送的string `reply`没有发现问题。有什么可能的原因导致这个错误呢？

``` 
 Traceback (most recent call last):
  File "main.py", line 229, in <module>
    itchat.run()
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/register.py", line 78, in run
    while self.alive: self.configured_reply()
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/register.py", line 51, in configured_reply
    r = replyFn(msg)
  File "main.py", line 28, in reply_text
    itchat.send(reply, msg['FromUserName'])
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/messages.py", line 370, in send
    r = self.send_msg(msg, toUserName)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/messages.py", line 225, in send_msg
    r = self.send_raw_msg(1, msg, toUserName)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/messages.py", line 221, in send_raw_msg
    data=json.dumps(payloads, ensure_ascii=False).encode('utf8'))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by nmweizi** [comment]
有同样的问题和现象

**Comment by littlecodersh** [comment]
@qing6010 手机保持在线吗？

**Comment by qing6010** [comment]
可能有，这个不能100%肯定。但是之前手机有强制kill掉微信一段时间，然后再打开微信，发现机器人会自己自动回复。感觉若是这个原因，除非很长时间不登录？我可以测试下

**Comment by littlecodersh** [comment]
@qing6010 保持手机在线可能是一个解决方案，如果保持在线后依旧存在该问题的，我们可以再讨论。微信后台是会检测登陆网页版微信所用的手机端是否在线，若不在线会拒绝连接。

**Comment by qing6010** [comment]
@littlecodersh 确保手机在线后一天都没有断，大概就是这个原因。界面上catch这个error并提示就更好。可关了

**Comment by littlecodersh** [comment]
@qing6010 好的
