### ISSUE TITLE
Python 3 `update_chatroom` 分页运算兼容性问题

### ISSUE THREAD

**Issue by blueset** [littlecodersh/ItChat#184]
```
>>> itchat.update_chatroom("@@ba10281105bd1d584ba0b5d1f81c2b77bc7eed6b536d158fe19e0d2980b65f85", True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/itchat/components/contact.py", line 68, in update_chatroom
    for i in range(len(chatroom['MemberList']) / MAX_GET_NUMBER + 1):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by littlecodersh** [comment]
@blueset 感谢支持，将在新版本中修复。
