### ISSUE TITLE
添加好友出错

### ISSUE THREAD

**Issue by anderson916** [littlecodersh/ItChat#187]
```python
    itchat.add_friend(member["UserName"])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/itchat/components/contact.py", line 316, in add_friend
    if autoUpdate: self.update_friend(userName)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/itchat/components/contact.py", line 98, in update_friend
    return r if 1 < len(r) else r[0]
IndexError: list index out of range
````

**Comment by littlecodersh** [comment]
@anderson916 已在新版本中修复该问题，感谢你的支持！

**Comment by 9cat** [comment]
建议在说新版本中修复的时候，能说一下commit的号或者版本号会更好：）

**Comment by littlecodersh** [comment]
@9cat 好，下次我会带上的。

**Comment by andybirdgir** [comment]
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as Andy Yuqinyang. Py
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\wechat try easy.py", line 7, in <module>
    itcaht_user_name = itchat.search_friends(name=send_userid)[0]['UserName']
IndexError: list index out of range
请问这是怎么回事？？？
