### ISSUE TITLE
重复出现 Failed to get QR Code

### ISSUE THREAD

**Issue by 9cat** [littlecodersh/ItChat#19]
[INFO] Getting uuid
[INFO] Getting QR Code
[INFO] Getting uuid
[INFO] Getting QR Code
[INFO] Getting uuid
[INFO] Getting QR Code
[INFO] Getting uuid
[INFO] Getting QR Code
[INFO] Failed to get QR Code, please restart the program

这是什么原因， 是不是哪里修改什么参数才能正常运行？

就是以便下这些代码：
```python
import itchat

itchat.auto_login()

@itchat.msg_register
def simple_reply(msg):
    if msg.get('Type', '') == 'Text':
        return 'I received: %s'%msg.get('Content', '')

itchat.run()
```

**Comment by littlecodersh** [comment]
@9cat 再次运行程序还是失败吗？

**Comment by 9cat** [comment]
@littlecodersh  是的，   是需要修改appid之类的吗？ 另外，我不在中国境内， 会有影响吗？

**Comment by littlecodersh** [comment]
@9cat 你能够正常登陆`https://login.weixin.qq.com`吗？

**Comment by 9cat** [comment]
可以的， 出现：
![image](https://cloud.githubusercontent.com/assets/1379110/16111869/7de2e10c-3369-11e6-96c3-4f251f012f12.png)

**Comment by littlecodersh** [comment]
试试看这个测试程序：
```python
import requests, itchat, platform, subprocess, os

uuid = itchat.get_QRuuid()
url = '%s/qrcode/%s'%('https://login.weixin.qq.com', uuid)
r = requests.get(url, stream = True)
QR_DIR = 'QR.jpg'
with open(QR_DIR, 'wb') as f: f.write(r.content)
if platform.system() == 'Darwin':
    subprocess.call(['open', QR_DIR])
elif platform.system() == 'Linux':
    subprocess.call(['xdg-open', QR_DIR])
else:
    os.startfile(QR_DIR)
```

**Comment by 9cat** [comment]
出现找不到文件： （不过我在目录中倒是看到QR.jpg）
```
Traceback (most recent call last):
  File "test3.py", line 11, in <module>
    subprocess.call(['xdg-open', QR_DIR])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


```

**Comment by littlecodersh** [comment]
@9cat 那就需要找一个方法显示二维码，我这里有一个基础的解决方案：[这里](https://github.com/littlecodersh/EasierLife/tree/master/Plugins/QRCode)

**Comment by 9cat** [comment]
我这样就能显示了。 QR_DIR 必须可以双引号，单引号不行。

```python 
import requests, itchat, platform, subprocess, os

uuid = itchat.get_QRuuid()
url = '%s/qrcode/%s'%('https://login.weixin.qq.com', uuid)
r = requests.get(url, stream = True)
QR_DIR = "./QR.jpg"

print uuid
with open(QR_DIR, 'wb') as f: f.write(r.content)


print QR_DIR
if platform.system() == 'Darwin':
    subprocess.call(['open', QR_DIR])
elif platform.system() == 'Linux':
    subprocess.call(['cacaview', QR_DIR])
else:
    os.startfile(QR_DIR)
```

**Comment by 9cat** [comment]
这个QRCODE 显示有意思：


```python
import requests, itchat, platform, subprocess, os

from PIL import Image
import sys

BLOCK = 'MM'
class QRCode():
    def __init__(self, fileName, size, padding = 0, background = 'BLACK'):
        self.size = size
        self.padding = padding
        self.img = Image.open(fileName)
        self.times = self.img.size[0]/(size + padding * 2)
        self.rgb = self.img.convert('RGB')
        self.white = BLOCK if background == 'BLACK' else '  '
        self.black = '  ' if background == 'BLACK' else BLOCK
    def print_qr(self):
        sys.stdout.write(' '*50 + '\r')
        sys.stdout.flush()
        print(self.white * (self.size + 2))
        startPoint = self.padding + 0.5
        for y in range(self.size):
            sys.stdout.write(self.white)
            for x in range(self.size):
                r,g,b = self.rgb.getpixel(((x + startPoint) * self.times, (y + startPoint) * self.times))
                sys.stdout.write(self.white if r > 127 else self.black)
            print(self.white)
        print(self.white * (self.size + 2))


uuid = itchat.get_QRuuid()
url = '%s/qrcode/%s'%('https://login.weixin.qq.com', uuid)
r = requests.get(url, stream = True)
QR_DIR = './QR.jpg'

print uuid
with open(QR_DIR, 'wb') as f: f.write(r.content)

print QR_DIR
if platform.system() == 'Darwin':
    subprocess.call(['open', QR_DIR])
elif platform.system() == 'Linux':
#    subprocess.call(['cacaview', QR_DIR])
    q =  QRCode(QR_DIR, 37, 3, 'BLACK')
    q.print_qr()
else:
    os.startfile(QR_DIR)

```

**Comment by littlecodersh** [comment]
@9cat ！是我疏忽了，非常感谢

**Comment by 9cat** [comment]
@littlecodersh  感谢， 大功告成！ 能自动回复所以有信息了。
