### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by cubesky** [littlecodersh/ItChat#226]
2017-02-11 09:56:20,078: itchat [ERROR]
    Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/itchat/components/login.py", line 207, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "/usr/local/lib/python3.4/dist-packages/itchat/components/messages.py", line 166, in produce_msg
    msg = update_local_uin(core, m)
  File "/usr/local/lib/python3.4/dist-packages/itchat/components/contact.py", line 239, in update_local_uin
    newFriendDict['Uin'] = uin
TypeError: 'NoneType' object does not support item assignment

**Comment by littlecodersh** [comment]
@cubesky itchat版本是多少？

**Comment by cubesky** [comment]
@littlecodersh 1.2.22 (Python 3.4.3)

**Comment by littlecodersh** [comment]
@cubesky 竟然普通用户也会出现无法更新到的情况，将在下个版本里更新。
