### ISSUE TITLE
auto_login执行出错

### ISSUE THREAD

**Issue by HejiaHo** [littlecodersh/ItChat#246]
```python
import itchat
itchat.auto_login()
```

```bash
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/itchat/utils.py", line 123, in test_connect
    r = requests.get(config.BASE_URL)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

You can't get access to internet or wechat domain, so exit.
```

**Comment by featheraaa** [comment]
这是requests的错误 你用的是哪个requests版本，我也是有类似的错误

**Comment by littlecodersh** [comment]
@HejiaHo 字面意思，CERTIFICATE_VERIFY_FAILED

**Comment by HejiaHo** [comment]
@littlecodersh 有什么办法解决吗？

**Comment by littlecodersh** [comment]
@HejiaHo 这就是requests和urllib3的问题了，你可以自己搜一下。

**Comment by l123456789jy** [comment]
`pip uninstall -y certifi`
`pip install certifi==2015.04.28`

即可解决  py版本2.7.9

**Comment by ghostlyman** [comment]
可能是python版本内部的根证书过期，请尝试下列命令。
```
$ sudo pip uninstall -y certifi
$ sudo pip install certifi==2015.04.28
```
