### ISSUE TITLE
收到微信中的表情（非图片）时会报错

### ISSUE THREAD

**Issue by xwzy** [littlecodersh/ItChat#263]
```bash
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\itchat\components\register.py", line 68, in configured_reply
    self.send(r, msg.get('FromUserName'))
  File "C:\Python27\lib\site-packages\itchat\components\messages.py", line 408, in send
    r = self.send_image(msg[5:], toUserName)
  File "C:\Python27\lib\site-packages\itchat\components\messages.py", line 340, in send_image
    r = self.upload_file(fileDir, isPicture=not fileDir[-4:] == '.gif')
  File "C:\Python27\lib\site-packages\itchat\components\messages.py", line 275, in upload_file
    return ReturnValue(rawResponse=r)
UnboundLocalError: local variable 'r' referenced before assignment
```

**Comment by littlecodersh** [comment]
@xwzy 这是由于微信表情并非所有图片都可以下载，网页版里很多表情是无法下载到本地的。
发送空文件的bug已经在新版本中修复。
