### ISSUE TITLE
NameError: name 'update_local_friends' is not defined

### ISSUE THREAD

**Issue by xo0** [littlecodersh/ItChat#270]
Traceback (most recent call last):
  File "D:/PythonProjects/PycharmProjects/itchat/bot.py", line 7, in <module>
    itchat.auto_login(hotReload=True, enableCmdQR=False)
  File "D:\Python\lib\site-packages\itchat\components\register.py", line 27, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback):
  File "D:\Python\lib\site-packages\itchat\components\hotreload.py", line 69, in load_login_status
    update_local_friends(self, [contact])
NameError: name 'update_local_friends' is not defined

.29版本 有时候出现这个情况  需要删除itchat.pk1再扫二维码才没错误

**Comment by tempdban** [comment]
抱歉这个是我的错， 改完代码没跑一遍，这个是我极其不专业的地方。
再次抱歉

**Comment by tempdban** [comment]
诶 下次一定注意。
