### ISSUE TITLE
跌线后不会退出 run()

### ISSUE THREAD

**Issue by featheraaa** [littlecodersh/ItChat#275]
mainloop里面的
i = sync_check(self) 
当i !=None 与不等于0的时候。可能还有其它选项作者没有考虑到，把它当信息来处理，所以 不会退出run吧

**Comment by littlecodersh** [comment]
@featheraaa 是的，有关于这几个值的思路吗？
我照搬的网页版js的处理，就当他仍旧在线。
另外，我这里有过一段时间没有消息之后没有任何操作自动恢复的情况，所以没有考虑直接退出。

**Comment by featheraaa** [comment]
还是自动退出来好，不然跌线这么重要的事都 不知道。给个参数让用户自定义，要恢复还是退出

**Comment by littlecodersh** [comment]
@featheraaa 好呀，关于sync_check的返回值有什么研究的进展吗？我这个贴开着做个收集吧。
返回值是这样的：
```python
window.synccheck={retcode:"xxx",selector:"xxx"}
```
主要内容是，各位有没有见过除了0,2,6之外的一切正常的selector返回值？
另外，retcode有没有除了0之外一切正常的返回值？

**Comment by featheraaa** [comment]
http://pan.baidu.com/s/1hsn5jNY
这是百度云网盘，抓到这个请求，整理了一下，请下载看一下，txt文本来的，这里发出来可能长，很乱
在网页版 上的时候，服务器对sync爱理不理，有时有回应，有时候不返回，但当送以上一条数据后，服务器好像每条个sync都必回 webwxstatreport（web微信状态报告，感觉就像是这个意思）
这是不是能解决掉线问题呢
https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxstatreport?fun=new。。。。。

**Comment by featheraaa** [comment]
@littlecodersh 
http://pan.baidu.com/s/1hsn5jNY
这是百度云网盘，抓到这个请求，整理了一下，请下载看一下，txt文本来的，这里发出来可能长，很乱
在网页版 上的时候，服务器对sync爱理不理，有时有回应，有时候不返回，但当送以上一条数据后，服务器好像每条个sync都必回 webwxstatreport（web微信状态报告，感觉就像是这个意思）
这是不是能解决掉线问题呢
https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxstatreport?fun=new。。。。。

**Comment by featheraaa** [comment]
有时候一照二维码不一下就掉线，感觉以上的请求可以救一下掉线问题

**Comment by featheraaa** [comment]
这个难道是页面布局？

**Comment by littlecodersh** [comment]
@featheraaa 我研究一下

**Comment by featheraaa** [comment]
@littlecodersh 
测试挂了两天了，还有没出结果，继续修改了一下itchat源代码，在适当的时候打印出错误来，继续测试中

**Comment by featheraaa** [comment]
aceback (most recent call last):
File "site-packages\requests\adapters.py", line 423, in send
File "site-packages\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
File "site-packages\requests\packages\urllib3\util\retry.py", line 347, in increment
File "site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
File "site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
File "site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
File "", line 2, in raise_from
File "site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
File "http\client.py", line 1198, in getresponse
File "http\client.py", line 297, in begin
File "http\client.py", line 266, in _read_status
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "itchat\components\login.py", line 249, in maintain_loop
File "itchat\components\login.py", line 317, in get_msg
File "site-packages\requests\sessions.py", line 535, in post
File "site-packages\requests\sessions.py", line 488, in request
File "site-packages\requests\sessions.py", line 609, in send
File "site-packages\requests\adapters.py", line 473, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

Traceback (most recent call last):
File "site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
File "site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
File "", line 2, in raise_from
File "site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
File "http\client.py", line 1198, in getresponse
File "http\client.py", line 297, in begin
File "http\client.py", line 258, in _read_status
File "socket.py", line 576, in readinto
File "ssl.py", line 937, in recv_into
File "ssl.py", line 799, in read
File "ssl.py", line 583, in read
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

买了几个微信号，专 门来测试这些错误 ，目前这两个错误最多，远程 主机拒绝连接最多，但为什么会远程 拒绝连接，现在正在研究这个问题，线路是没有问题的，租了阿里的服务器。还有一个是错误是概率 性的
oldChatroom['OwnerUin'] = utils.search_dict_list(oldChatroom['MemberList'],
'UserName', oldChatroom['ChatRoomOwner']).get('Uin', 0)
在这一行 抛出的错误意思是 Notype 没有get方法，有时候一扫码就会有，但不是每次都 会有

**Comment by featheraaa** [comment]
Start auto replying.
2           -------------------------------------sync_check(self)返回后就出现下同的错误了，应该是在self.get_msg()出了问题，返回2又不让取消息被迫下线，看了下他们的 issues 他们说的同步线路问题


Traceback (most recent call last):
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
  File "http\client.py", line 1198, in getresponse
  File "http\client.py", line 297, in begin
  File "http\client.py", line 258, in _read_status
  File "socket.py", line 576, in readinto
  File "ssl.py", line 937, in recv_into
  File "ssl.py", line 799, in read
  File "ssl.py", line 583, in read
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
  File "site-packages\requests\packages\urllib3\util\retry.py", line 347, in increment
  File "site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
  File "http\client.py", line 1198, in getresponse
  File "http\client.py", line 297, in begin
  File "http\client.py", line 258, in _read_status
  File "socket.py", line 576, in readinto
  File "ssl.py", line 937, in recv_into
  File "ssl.py", line 799, in read
  File "ssl.py", line 583, in read
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关 闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "itchat\components\login.py", line 250, in maintain_loop
  File "itchat\components\login.py", line 321, in get_msg
  File "site-packages\requests\sessions.py", line 535, in post
  File "site-packages\requests\sessions.py", line 488, in request
  File "site-packages\requests\sessions.py", line 609, in send
  File "site-packages\requests\adapters.py", line 473, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

LOG OUT!





def maintain_loop():
        retryCount = 0
        #------------------------------------------------
        mytime = time.time()  #改了这一行
        #------------------------------------------------
        while self.alive:

            

            
            try:
                i = sync_check(self)
                if i is None:
                    self.alive = False
                elif i == '0':
                    #------------------------------------------------
                    if time.time() - mytime >=1500:  #改了这一行 如果超过一千五百秒无信息，退出
                        self.alive = False  #改了这一行
                        logger.info(' log out in mytime ') #改了这一行，到最后都没有输出 
                        break
                    #------------------------------------------------
                else:
                    msgList, contactList = self.get_msg()
                    if msgList:
                        msgList = produce_msg(self, msgList)
                        for msg in msgList:
                            self.msgList.put(msg)
                    if contactList:
                        chatroomList, otherList = [], []
                        for contact in contactList:
                            if '@@' in contact['UserName']:
                                chatroomList.append(contact)
                            else:
                                otherList.append(contact)
                        chatroomMsg = update_local_chatrooms(self, chatroomList)
                        self.msgList.put(chatroomMsg)
                        update_local_friends(self, otherList)
                        #------------------------------------------------
                        mytime = time.time() #改了这一行
                        #------------------------------------------------
                retryCount = 0#改了这一行, 缩进了一下，只要有动作才等于0, self.retryCoun改成了15
                
            except:
                logger.info(str(i))  retryCoun
                retryCount += 1
                logger.error(traceback.format_exc())
                if self.receivingRetryCount < retryCount:
                    self.alive = False
                else:
                    time.sleep(1)


看了下他们的 issues 他们说的同步线路问题,刚刚才看到，我掉线的号是个淘宝最便宜的外国号，晕啊
https://github.com/Urinx/WeixinBot/issues/114
至于卡死的问题，是控制台输出太多的异常了，所以就不返应了

**Comment by featheraaa** [comment]
Traceback (most recent call last):
  File "itchat\components\login.py", line 249, in maintain_loop
  File "itchat\components\login.py", line 319, in get_msg
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by featheraaa** [comment]
Start auto replying.
Traceback (most recent call last):
  File "itchat\components\login.py", line 261, in maintain_loop
  File "itchat\storage.py", line 11, in _contact_change
  File "itchat\components\contact.py", line 170, in update_local_chatrooms
AttributeError: 'NoneType' object has no attribute 'get'
终于让我看到了这个

**Comment by tempdban** [comment]
先说主机强迫关闭的问题，不是说你用的阿里云线路就一定稳定。还有当到达微信服务器最大处理能力的时候，会不会把你T掉也是未知数。发生ssl报的错，除了重试，基本没别的办法。
json.decoder.JSONDecodeError: 这个错也是微信服务器的锅，现在itchat代码里没有进行重新连接。
最后一个异常，你是什么版本的，最新版本170行我没看到有get啊

**Comment by featheraaa** [comment]
@tempdban 
其实我很想解决这个问题，买了好多个微信号去试，真的，我的线路比一般人的都优秀
ping 过微信服务器，发现它在上海，特意把服务器租到上海 不过确实线路也只有 3MS延迟，怀疑微信服务器正在我的服务器隔壁，最后一个get错误是概率性的，不是每次都有。但有很多时候，itchat提示退出，我打开手机一看，实际上手机上没有显示退出，也许是我改的代码不合适。我再试试

**Comment by featheraaa** [comment]
正如大家所说，selector返回的数字大家都不知道什么4呀，7呀是什么意思
听说fiddler可以通过脚本拦截并改变返回来的东西，过几天我用fiddler试试把返回来的 selector改成4，7之类,
看浏览器有什么反应，说不定能弄出点结果来，只是现在还没弄清楚fildder用的是什么脚本去的。我学学看

**Comment by featheraaa** [comment]
@tempdban 
我用的是python3.5 itchat 1.2.29

**Comment by youfou** [comment]
@featheraaa 
推荐 **mitmproxy**，虽然是console app，但因为有上下文帮助，使用体验不输 Fiddler。
Mitmproxy 本身是 Python 写的，支持使用 Python 脚本修改 request/response flow，还支持通过安装证书的方式嗅探 HTTPS 协议。

**Comment by featheraaa** [comment]
兄弟们，试了一天了，fiddler是抓到包，就是无法修改response，拉截修改后，从浏览器上看还是返回一样的数据，不知道怎么回事。有没有人会抓会改的？
关于不会退出的话是logger.error(traceback.format_exc())
这一句里，
控制台输出太多直接卡死所至，我用的是windows 2016数据版

**Comment by featheraaa** [comment]
seleltor 是7也不会退出

**Comment by featheraaa** [comment]
@youfou 
早知道用你那个的，折腾了这么久，白弄了。我过几天，再试试

**Comment by featheraaa** [comment]
Traceback (most recent call last):
  File "itchat\components\register.py", line 66, in configured_reply
  File "4..py", line 274, in text_reply
KeyError: 'ActualNickName'    这一行报错了  msg['ActualNickName']
 window.synccheck={retcode:"0",selector:"3"}  #3也是正常，但不知道什么意思

**Comment by youfou** [comment]
@littlecodersh @featheraaa 我应该找到原因了


是因为 itchat 的 `“synccheck”` 和 `“webwxsync”` 两个请求，未设置 `timeout` 参数。
本身是个细节问题。


----


我在 `Requests` 模块的文档中找到 ([原文](http://docs.python-requests.org/en/master/user/advanced/#timeouts))
> By default, requests do not time out unless a timeout value is set explicitly.


也就是说，如果没有明确设置 `timeout` 的话，请求可能会永远等待，不会返回。


----


**我们可以做个小实验来验证**


1. 使用 itchat 登陆微信
2. 在登陆成功后，断开电脑的网络连接


至少我这里的现象是，**程序会一直“保持”登陆状态，不会自动登出。**


----


而前面提到的这两个请求，均位于消息线程 `start_receiving()` 中，并且是在同一个线程中交替进行。


也就是说，只要其中一个请求 (因网络等问题) 被 hold 住，这个线程就会永远停在那里。


----


**这将导致两个问题**


1. 数分钟后，因为没有上报新的心跳而在微信服务端被登出 (此时发送消息会出现 `1101` 错误)
2. “登出”操作也因在同个线程中而无法执行，“保持”登陆状态


----


我在 wxpy 的开发分支上，通过特别的方式为以上两个请求增加了 `timeout` 参数 ([代码](https://github.com/youfou/wxpy/blob/fc708a6326d8b406ebefe9ff29d7a3265cf5d76e/wxpy/utils/misc.py#L279))。


**修改后的效果**


1. 现在再次进行上面的小实验，**程序会在断网后自动登出了**
2. 如果设想成立，这个修改还 **能有效提升机器人保持在线的稳定性**

----

**在 itchat 中修改**

只需在两个请求中分布加入 `timeout` 参数即可，请见 PR #347

**Comment by featheraaa** [comment]
@littlecodersh @youfou 
 requests要有timeout是对的，非常厉害
最近几个月没上github，想在周末来解决这个问题的，竟然解决了

**Comment by featheraaa** [comment]
@littlecodersh @tempdban 
问题已经解决了

**Comment by featheraaa** [comment]
i = sync_check(self)
                if i is None:
                    tryagin = tryagin -1 #这里建议加点东西 ，因为requests timeout可能返回None
                    if tryagin <= 0:
                        self.alive = False
                    time.sleep(0.5)
                    continue
建议作者 加上这些东西，因为timeout超时不一定已掉线，

**Comment by featheraaa** [comment]
即使是itchat.run()已结退出 但我在后来还能收到retcode:0 seletor:2之类的东西，请作者重视 
因为timeout超时不一定已掉线，

**Comment by suntong** [comment]
问题已经解决了?
