### ISSUE TITLE
py3版本bug：发送文件出错

### ISSUE THREAD

**Issue by pcloth** [littlecodersh/ItChat#29]
@littlecodersh @Chyroc 两位老大，麻烦给看看，不知道是不是我自己弄错了什么？

**执行代码：**
```python
itchat.send_file('2016.xls',self.user)
```

**错误信息：**
```bash
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:/code/weixinBot/weixinrot 个人号.py", line 132, in run
    itchat.send_file('2016.xls',self.user)
  File "D:\Anaconda3\lib\site-packages\itchat\__init__.py", line 87, in send_file
    return __client.send_file(fileDir, toUserName)
  File "D:\Anaconda3\lib\site-packages\itchat\client.py", line 628, in send_file
    mediaId = self.__upload_file(fileDir)
  File "D:\Anaconda3\lib\site-packages\itchat\client.py", line 614, in __upload_file
    }, separators=(',', ':'))),
  File "D:\Anaconda3\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "D:\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Anaconda3\lib\json\encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'9I/loYJ4Kl4fVPsS' is not JSON serializable
```

**Comment by littlecodersh** [comment]
@pcloth 这是我们这里程序的bug
不过我不用python3只能粗略的先帮你改一下，更新程序版本的事情要交给@Chyroc了

**解决方案如下**
修改一下`D:\Anaconda3\lib\site-packages\itchat\client.py`的`__upload_file`内容为：
```python
def __upload_file(self, fileDir, isPicture=False):
    if not tools.check_file(fileDir): return
    url = 'https://file%s.wx.qq.com/cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json' % (
        '2' if '2' in self.loginInfo['url'] else '')
    # save it on server
    fileSize = str(os.path.getsize(fileDir))
    cookiesList = {name: data for name, data in self.s.cookies.items()}
    fileType = mimetypes.guess_type(fileDir)[0] or 'application/octet-stream'
    files = {
        'id': (None, 'WU_FILE_0'),
        'name': (None, os.path.basename(fileDir)),
        'type': (None, fileType),
        'lastModifiedDate': (None, time.strftime('%a %b %d %Y %H:%M:%S GMT+0800 (CST)')),
        'size': (None, fileSize),
        'mediatype': (None, 'pic' if isPicture else 'doc'),
        'uploadmediarequest': (None, json.dumps({
            'BaseRequest': {k: v.decode('ascii') for k, v in self.loginInfo['BaseRequest'].items()},
            'ClientMediaId': int(time.time()),
            'TotalLen': fileSize,
            'StartPos': 0,
            'DataLen': fileSize,
            'MediaType': 4,
        }, separators=(',', ':'))),
        'webwx_data_ticket': (None, cookiesList['webwx_data_ticket']),
        'pass_ticket': (None, 'undefined'),
        'filename': (os.path.basename(fileDir), open(fileDir, 'rb'), fileType),
    }
    headers = {
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36'
    }
    r = self.s.post(url, files=files, headers=headers)
    return json.loads(r.text)['MediaId']
```

**通过测试的程序**
```python
#!python3
import itchat

itchat.auto_login()
itchat.send('@fil@test.py')
```

**Comment by littlecodersh** [comment]
完成更新：[Fix upload file bug](https://github.com/littlecodersh/ItChat/commit/6a5ae68c32db1ba305462da2b2e97be94e4f38d0)
