### ISSUE TITLE
收到输入法自带的表情（非图片）时会报错

### ISSUE THREAD

**Issue by zhihuaqiu** [littlecodersh/ItChat#309]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
Traceback (most recent call last):
  File "C:\Users\zhihuaqiu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\itchat\components\register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "C:\Users\zhihuaqiu\Desktop\wx\wMsg.py", line 198, in Revocation
    print("消息提取", msg_content)
  File "C:\Users\zhihuaqiu\AppData\Local\Programs\Python\Python36-32\lib\idlelib\run.py", line 348, in write
    return self.shell.write(s, self.tags)
  File "C:\Users\zhihuaqiu\AppData\Local\Programs\Python\Python36-32\lib\idlelib\rpc.py", line 604, in __call__
    value = self.sockio.remotecall(self.oid, self.name, args, kwargs)
  File "C:\Users\zhihuaqiu\AppData\Local\Programs\Python\Python36-32\lib\idlelib\rpc.py", line 216, in remotecall
    return self.asyncreturn(seq)
  File "C:\Users\zhihuaqiu\AppData\Local\Programs\Python\Python36-32\lib\idlelib\rpc.py", line 247, in asyncreturn
    return self.decoderesponse(response)
  File "C:\Users\zhihuaqiu\AppData\Local\Programs\Python\Python36-32\lib\idlelib\rpc.py", line 267, in decoderesponse
    raise what
UnicodeEncodeError: 'UCS-2' codec can't encode character '\U0001f602' in position 0: Non-BMP character not supported in Tk
```

您的itchat版本为：`[1.3.4]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [接收到搜狗输入法自带的表情时会报错，类似这种：
![qq 20170329150348](https://cloud.githubusercontent.com/assets/16696699/24442477/ee807470-1490-11e7-8cc8-496326575140.png)
]

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by littlecodersh** [comment]
@zhihuaqiu 非本项目相关问题，故关闭。
