### ISSUE TITLE
linux运行相关

### ISSUE THREAD

**Issue by sunnysuhappy** [littlecodersh/ItChat#312]
在linux上面运行，不通过enableCmdQR的方式登录，报错。错误信息如下

```python
Getting uuid of QR code.
Downloading QR code.
Traceback (most recent call last):
  File "itchatlogin.py", line 2, in <module>
    itchat.auto_login( enableCmdQR=False, picDir='pic')
  File "/root/virtualenvs/itchat/lib/python2.7/site-packages/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/root/virtualenvs/itchat/lib/python2.7/site-packages/itchat/components/login.py", line 45, in login
    picDir=picDir, qrCallback=qrCallback)
  File "/root/virtualenvs/itchat/lib/python2.7/site-packages/itchat/components/login.py", line 118, in get_QR
    utils.print_qr(picDir)
  File "/root/virtualenvs/itchat/lib/python2.7/site-packages/itchat/utils.py", line 83, in print_qr
    subprocess.call(['xdg-open', fileDir])
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

cmdQR的方式出来的图片扫描无能，怎么扫都扫不出来，我感觉二维码的边界的透明像素也被画上像素了，就扫不出来了是这样的
![image](https://cloud.githubusercontent.com/assets/2516790/24745631/f11e741c-1ae8-11e7-88b6-73b1b8b68174.png)

求助怎么在服务器上面跑

**Comment by tempdban** [comment]
https://github.com/littlecodersh/ItChat/blob/master/README.md#命令行二维码
