### ISSUE TITLE
Group Chat Message Listening Bug

### ISSUE THREAD

**Issue by jinfagang** [littlecodersh/ItChat#333]
I am trying to listening simple group chat message, get these messge:
```
Traceback (most recent call last):
  File "/itchat/components/login.py", line 251, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "/itchat/components/messages.py", line 65, in produce_msg
    produce_group_chat(core, m)
  File "/itchat/components/messages.py", line 259, in produce_group_chat
    atFlag = '@' + chatroom['Self'].get('DisplayName', core.storageClass.nickName)
KeyError: 'Self'

Tue, 25 Apr 2017 10:14:08 login.py[line:268] ERROR Traceback (most recent call last):
  File "itchat/components/login.py", line 251, in maintain_loop
    msgList = produce_msg(self, msgList)
  File "/itchat/components/messages.py", line 65, in produce_msg
    produce_group_chat(core, m)
  File "itchat/components/messages.py", line 259, in produce_group_chat
    atFlag = '@' + chatroom['Self'].get('DisplayName', core.storageClass.nickName)
KeyError: 'Self'
```

Any idea how this happen?

**Comment by tempdban** [comment]
什么版本

**Comment by jinfagang** [comment]
Seems cache problem, I delete all chatroom works fine now.
