### ISSUE TITLE
调用itchat.add_member_into_chatroom(chatroom, friend_list, useInvitation=True) 报错

### ISSUE THREAD

**Issue by superchaoran** [littlecodersh/ItChat#337]
Source Code:
# 收到好友邀请自动添加好友
@itchat.msg_register(FRIENDS)
def add_friend(msg):
	print("New Friend:"+ json.dumps(msg))
	itchat.add_friend(**msg['Text']) # 该操作会自动将新好友的消息录入，不需要重载通讯录
	itchat.send_msg('Nice to meet you!', msg['RecommendInfo']['UserName'])
	chatroomName='天天健身'
	itchat.get_chatrooms(update=True)
	chatrooms = itchat.search_chatrooms(name=chatroomName)
	if chatrooms is None:
		print(u'没有找到群聊：' + chatroomName)
	else:
		chatroom = itchat.update_chatroom(chatrooms[0]['UserName'])
		print('\n\n\n')
		print(json.dumps(msg))
		friend_list = []
		friend_list.append(msg['RecommendInfo']['UserName'])
		print(friend_list)
		itchat.add_member_into_chatroom(chatroom, friend_list, useInvitation=True) 

log```

{"AppInfo": {"Type": 0, "AppID": ""}, "ImgWidth": 0, "FromUserName": "fmessage", "PlayLength": 0, "OriContent": "", "ImgStatus": 1, "RecommendInfo": {"UserName": "@b6bccc0620e8a921469cea85c50733fca93e17b58f32dfc35ff483b7a880c45d", "Province": "Illinois", "City": "Champaign City", "Scene": 33, "QQNum": 0, "Content": "I'm \u8d85\u7136", "Alias": "", "OpCode": 2, "Signature": "", "Ticket": "v2_34b25396141408356a54399b1aa29de9242c549568a0ebcdcaf3a8c0c8d52efd08a28edbd33539aca11d877aac62d0a7f749949d5ff45e3cdf0fd0ffb47beb15@stranger", "Sex": 1, "NickName": "\u8d85\u7136", "AttrStatus": 71401479, "VerifyFlag": 0}, "Content": "<msg fromusername=\"wxid_5xj97mxrnnrb11\" encryptusername=\"v1_f879a0d8d6f5f47d0158fb96ebfa2b2ba7efa087aca86a7fa534149343ea177c13af0e0e0d4c69e3d8c8e6ef8926ba4b@stranger\" fromnickname=\"\u8d85\u7136\" content=\"I&apos;m \u8d85\u7136\"  shortpy=\"CR\" imagestatus=\"3\" scene=\"33\" country=\"US\" province=\"Illinois\" city=\"Champaign City\" sign=\"\" percard=\"1\" sex=\"1\" alias=\"superchaoran\" weibo=\"\" weibonickname=\"\" albumflag=\"0\" albumstyle=\"0\" albumbgimgid=\"897399056760833_897399056760833\" snsflag=\"49\" snsbgimgid=\"http://mmsns.qpic.cn/mmsns/4376ae1e0cf0ccced233def9ad1560d0dec29d64941ab85a5578c4416e6f4ce95788c834eea838b28f2c65dcb43496ee8ac745d905bb94e3/0\" snsbgobjectid=\"11912800236044623938\" mhash=\"\" mfullhash=\"\" bigheadimgurl=\"http://wx.qlogo.cn/mmhead/BO1qQiajiacVlGXtC6s15jUAquqER5T2gearVIOh6Noh6rPUKc2D1TSw/0\" smallheadimgurl=\"http://wx.qlogo.cn/mmhead/BO1qQiajiacVlGXtC6s15jUAquqER5T2gearVIOh6Noh6rPUKc2D1TSw/132\" ticket=\"v2_34b25396141408356a54399b1aa29de9242c549568a0ebcdcaf3a8c0c8d52efd08a28edbd33539aca11d877aac62d0a7f749949d5ff45e3cdf0fd0ffb47beb15@stranger\" opcode=\"2\" googlecontact=\"\" qrticket=\"\" chatroomusername=\"\" sourceusername=\"\" sourcenickname=\"\"><brandlist count=\"0\" ver=\"645111317\"></brandlist></msg>", "MsgType": 37, "StatusNotifyUserName": "", "ImgHeight": 0, "StatusNotifyCode": 0, "Type": "Friends", "NewMsgId": 933617372132111743, "Status": 3, "VoiceLength": 0, "MediaId": "", "MsgId": "933617372132111743", "ToUserName": "@1fe88ad0564a2a284c9e32ae55bb81b6a5c0153a4426314e5e87bc83704c8610", "ForwardFlag": 0, "FileName": "", "Url": "", "HasProductId": 0, "User": {"UserName": "@b6bccc0620e8a921469cea85c50733fca93e17b58f32dfc35ff483b7a880c45d", "MemberList": []}, "AppMsgType": 0, "Text": {"status": 3, "userName": "@b6bccc0620e8a921469cea85c50733fca93e17b58f32dfc35ff483b7a880c45d", "verifyContent": "", "autoUpdate": {"UserName": "@b6bccc0620e8a921469cea85c50733fca93e17b58f32dfc35ff483b7a880c45d", "Province": "Illinois", "City": "Champaign City", "Scene": 33, "QQNum": 0, "Content": "I'm \u8d85\u7136", "Alias": "", "OpCode": 2, "Signature": "", "Ticket": "v2_34b25396141408356a54399b1aa29de9242c549568a0ebcdcaf3a8c0c8d52efd08a28edbd33539aca11d877aac62d0a7f749949d5ff45e3cdf0fd0ffb47beb15@stranger", "Sex": 1, "NickName": "\u8d85\u7136", "AttrStatus": 71401479, "VerifyFlag": 0}}, "Ticket": "", "FileSize": "", "CreateTime": 1493363063, "SubMsgType": 0}
[u'@b6bccc0620e8a921469cea85c50733fca93e17b58f32dfc35ff483b7a880c45d']
Traceback (most recent call last):
  File "/Users/chaoran/anaconda/lib/python2.7/site-packages/itchat/components/register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "tiantian.py", line 57, in add_friend
    itchat.add_member_into_chatroom(chatroom, friend_list, useInvitation=True)
  File "/Users/chaoran/anaconda/lib/python2.7/site-packages/itchat/components/contact.py", line 488, in add_member_into_chatroom
    memberKeyName  : ','.join([member['UserName'] for member in memberList]), }
TypeError: string indices must be integers

```
调用itchat.add_member_into_chatroom(chatroom, friend_list, useInvitation=True) 报错

**Comment by superchaoran** [comment]
使用[{'UserName':msg['FromUserName']}]解决报错
