### ISSUE TITLE
一直跳出这个异常

### ISSUE THREAD

**Issue by rzwei** [littlecodersh/ItChat#353]
运行日志
```
Request to send a text message to filehelper: 2017-05-08 22-32-21

 2017-05-08 22-32-21 aliving! 

Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Program Files\Python\Python35\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python\Python35\lib\threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "F:/Users/rzhon/IdeaProjects/pythondebug/gxb1/weixin-itchat.py", line 560, in fun3
    itchat.send(replyMsg, name)
  File "F:\Users\rzhon\env\lib\site-packages\itchat\components\messages.py", line 489, in send
    elif msg[:5] == '@fil@':
TypeError: unhashable type: 'slice'

Request to send a text message to filehelper: 2017-05-08 22-39-52

 2017-05-08 22-39-52 aliving! 

Request to send a text message to @46c1d07d31b429b48ee8727c4640678ab3a770c412b8bff316ba5663d0733b79: *****
Traceback (most recent call last):
  File "F:\Users\rzhon\env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "F:\Users\rzhon\env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "F:\Users\rzhon\env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python\Python35\lib\http\client.py", line 1174, in getresponse
    response.begin()
  File "C:\Program Files\Python\Python35\lib\http\client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python\Python35\lib\http\client.py", line 270, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: HTTP/1.1 0 -


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Users\rzhon\env\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "F:\Users\rzhon\env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "F:\Users\rzhon\env\lib\site-packages\requests\packages\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "F:\Users\rzhon\env\lib\site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "F:\Users\rzhon\env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "F:\Users\rzhon\env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "F:\Users\rzhon\env\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python\Python35\lib\http\client.py", line 1174, in getresponse
    response.begin()
  File "C:\Program Files\Python\Python35\lib\http\client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python\Python35\lib\http\client.py", line 270, in _read_status
    raise BadStatusLine(line)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Users\rzhon\env\lib\site-packages\itchat\components\login.py", line 232, in maintain_loop
    i = sync_check(self)
  File "F:\Users\rzhon\env\lib\site-packages\itchat\components\login.py", line 285, in sync_check
    r = self.s.get(url, params=params, headers=headers)
  File "F:\Users\rzhon\env\lib\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "F:\Users\rzhon\env\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\Users\rzhon\env\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "F:\Users\rzhon\env\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))
```

itchat版本为：1.3.5

我使用itchat 写了个自动回复的机器人，但是最近经常调这个错误，没几次就掉了，原来好像不是这样的。。

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by littlecodersh** [comment]
@rzwei replyMsg的传入参数有误，你可以看一下[这个网址][so]。

[so]: http://stackoverflow.com/questions/40939911/unhashable-type-slice
