### ISSUE TITLE
代码200行,报ConnectionError: 报错的行数代码中找不到

### ISSUE THREAD

**Issue by superchaoran** [littlecodersh/ItChat#360]
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 232, in maintain_loop
    i = sync_check(self)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 285, in sync_check
    r = self.s.get(url, params=params, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))
```

**Comment by tempdban** [comment]
网络问题，捕获异常重发呗

**Comment by pengyuwei** [comment]
我也频繁碰到这个问题
