### ISSUE TITLE
接受好友请求并发送信息经常阻塞

### ISSUE THREAD

**Issue by Dkner** [littlecodersh/ItChat#361]
python版本：3.5.3
itchat版本为：`1.3.6`
场景：多开机器人接受大量的好友请求并回复开场白
现象：多线程开了4个机器人，有一个机器人收到两三百个好友请求时阻塞了，无法通过好友请求，其他机器人正常

```python
File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/itchat/components/register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "/opt/tools/weixin_robot/editor_robot.py", line 139, in add_friend
    robot.add_friend(**msg['Text'])
  File "/usr/local/python3/lib/python3.5/site-packages/itchat/components/contact.py", line 376, in add_friend
    data=json.dumps(data, ensure_ascii=False).encode('utf8', 'replace'))
  File "/usr/local/python3/lib/python3.5/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/itchat/components/login.py", line 232, in maintain_loop
    i = sync_check(self)
  File "/usr/local/python3/lib/python3.5/site-packages/itchat/components/login.py", line 285, in sync_check
    r = self.s.get(url, params=params, headers=headers, timeout=config.TIMEOUT)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/python3/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/python3/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/python3/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/python3/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 388, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/python3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:
```

## 核心代码：

```python
@itchat.msg_register([TEXT])
def text_reply(msg):
    global QR_MAX_TRIED_COUNT
    QR_MAX_TRIED_COUNT = 0

    def add_editor_qr_callback(uuid, status, qrcode):
        global QR_MAX_TRIED_COUNT
        if QR_MAX_TRIED_COUNT<2:
            pic_file = os.path.join(os.path.split(os.path.realpath(__file__))[0], 'editor_data', msg['FromUserName'] + '.png')
            with open(pic_file, 'wb') as f:
                f.write(qrcode)
            itchat.send('Please scan the QR code to log in.', msg['FromUserName'])
            itchat.send('@img@{}'.format(pic_file), msg['FromUserName'])
        elif QR_MAX_TRIED_COUNT>5 or str(status)=='408':
            itchat.send('Scan timeout, Please request again', msg['FromUserName'])
            //还有问题是我想账号长时间不扫描登录会阻塞，所以我直接exit，我看源代码没有退出的逻辑，这样用法有问题吗？跑的时候是正常的
            exit(0)
        QR_MAX_TRIED_COUNT += 1

    if '机器人' in msg['Text']:
        editor = ZongqunRobot(id=msg['FromUserName'], robot=itchat.new_instance())
        editor.run(add_editor_qr_callback)

class ZongqunRobot(EditorRobot):
    def __init__(self, id, robot):
        EditorRobot.__init__(self, id, robot)

        @robot.msg_register(FRIENDS)
        def add_friend(msg):
            robot.add_friend(**msg['Text'])
            auto_reply = '''hhh'''
            robot.send(auto_reply, msg['RecommendInfo']['UserName'])
            data_dir = os.path.join(os.path.split(os.path.realpath(__file__))[0], 'master_data')
            robot.send('@img@{}'.format(os.path.join(data_dir, choice(EditorRobot.editor_pic))), msg['RecommendInfo']['UserName'])

    def run(self, qr_callback):
        Dir = os.path.join(os.path.split(os.path.realpath(__file__))[0], 'editor_data')
        self.robot.auto_login(hotReload=True, statusStorageDir=os.path.join(Dir, self.id + '.pkl'),
                              picDir=os.path.join(Dir, self.id + '.png'), qrCallback=qr_callback)
        self.robot.run(blockThread=False)
```

**Comment by littlecodersh** [comment]
@Dkner 报错看是微信后台关闭了连接。
可能是因为好友添加频率过高导致这一情况。
