### ISSUE TITLE
config.py TIMEOUT 报错

### ISSUE THREAD

**Issue by NUPT-Pig** [littlecodersh/ItChat#362]
报错信息
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 232, in maintain_loop
    i = sync_check(self)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 285, in sync_check
    r = self.s.get(url, params=params, headers=headers, timeout=config.TIMEOUT)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 316, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/util.py", line 116, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/lib/python2.7/dist-packages/urllib3/util.py", line 147, in _validate_timeout
    "int or float." % (name, value))
ValueError: Timeout value connect was (10, 30), but it must be an int or float.
```

您的itchat版本为：`[1.3.6]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

好像是urllib不能处理TIMEOUT = (10, 30) 而是只能接收int和float型的。

**Comment by littlecodersh** [comment]
@NUPT-Pig 更新一下requests和urllib3
