### ISSUE TITLE
发现新问题

### ISSUE THREAD

**Issue by featheraaa** [littlecodersh/ItChat#383]
```bash
Traceback (most recent call last):
  File "itchat\components\login.py", line 245, in maintain_loop
  File "itchat\components\login.py", line 313, in get_msg
  File "json\__init__.py", line 318, in loads
  File "json\decoder.py", line 343, in decode
  File "json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by littlecodersh** [comment]
@featheraaa 看问题是微信返回的数据不是有效的json，应该是连接出问题了。
我这里有做重试：[代码][source]。

[source]: https://github.com/littlecodersh/ItChat/blob/master/itchat/components/login.py#L231-L261
