### ISSUE TITLE
启动时报错：SSL证书错误

### ISSUE THREAD

**Issue by vhyme** [littlecodersh/ItChat#386]
itchat v1.3.7 启动时报错提示SSL证书错误，在阿里云、腾讯云、bandwagon三个服务器上试过都是这样。

这三个服务器都曾经renew过一次SSL证书，不知道是不是跟这个有关，所以为什么我的服务器去登陆微信还需要我服务器的SSL？而且renew一次证书为什么就不能用了？😑

log如下：

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/itchat/utils.py", line 125, in test_connect
    r = requests.get(config.BASE_URL)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)

You can't get access to internet or wechat domain, so exit.
```

**Comment by tempdban** [comment]
跟你的ssl没关系，你是需要更新一下根证书了。

**Comment by ikkong** [comment]
```
sudo pip uninstall -y certifi
sudo pip install certifi==2015.04.28
```
可能会有用
[ssl - Python Requests throwing up SSLError](https://stackoverflow.com/questions/10667960/python-requests-throwing-up-sslerror)

**Comment by hdxiong** [comment]
我是通过这个方法解决的，certifi最新版是2017更新的，必须卸载用2015年的才行。

**Comment by mindcont** [comment]
大家好,我已经更新了本地证书,但错误还是发生
```css
pi@ubuntu:~/iot$ pip list | grep cert
certifi                            2018.4.16
```
我的代码
```css
# -*- coding: utf-8 -*-

from wxpy import *
import requests
import os
import random
import re

bot = Bot()

```

错误
```css
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/itchat/utils.py", line 124, in test_connect
    r = requests.get(config.BASE_URL)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))

You can't get access to internet or wechat domain, so exit.

```

**Comment by mindcont** [comment]
找到原因了,本地网络问题

而当手机开无线热点, PC端浏览器访问[https://login.weixin.qq.com](https://login.weixin.qq.com)正常显示后,再次运行ItChat正常

**Comment by UoUoio** [comment]
同样遇到这个问题 原来是因为我开了翻墙...
