### ISSUE TITLE
Linux 环境下hotReload login的时候报错

### ISSUE THREAD

**Issue by HevLfreis** [littlecodersh/ItChat#387]
itchat 1.3.7
环境Ubuntu 14.04，python 2.7.6
使用hotReload=True时候，报错，信息如下

Traceback (most recent call last):
  File "main.py", line 36, in <module>
    itchat.auto_login(enableCmdQR=2, hotReload=True)
  File "/home/hevlfreis/projects/iBot/venv/local/lib/python2.7/site-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/home/hevlfreis/projects/iBot/venv/local/lib/python2.7/site-packages/itchat/components/login.py", line 49, in login
    status = self.check_login()
  File "/home/hevlfreis/projects/iBot/venv/local/lib/python2.7/site-packages/itchat/components/login.py", line 132, in check_login
    process_login_info(self, r.text)
  File "/home/hevlfreis/projects/iBot/venv/local/lib/python2.7/site-packages/itchat/components/login.py", line 166, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-102: ordinal not in range(128)

r.text的信息打印如下
»å½ç¯å¢å¼å¸¸ãä¸ºäºä½ ç
<error><ret>1203</ret><message>å½å                       å¸å·å®å¨ï¼ææ¶ä¸è½ç»å½webå¾®ä¿¡ãä½ å¯ä»¥éè¿ææºå®¢æ·ç«¯æè
windowså¾®ä¿¡ç»å½ã</message></error>

代码没有用run的模式，就是简单的login之后send信息
在win环境测试的时候没有异常Anaconda 2.7.11

**Comment by tempdban** [comment]
尝试升级python到2.7 的最新版本

**Comment by keminggu** [comment]
我也遇到同样的问题，在mac os 挂载几天后，自动掉了，然后重新登录就一直报错

Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Traceback (most recent call last):
  File "login.py", line 182, in <module>
    main()
  File "login.py", line 175, in main
    itchat.auto_login(hotReload=True)
  File "/Users/evan/Desktop/ItChat/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Users/evan/Desktop/ItChat/itchat/components/login.py", line 49, in login
    status = self.check_login()
  File "/Users/evan/Desktop/ItChat/itchat/components/login.py", line 132, in check_login
    process_login_info(self, r.text)
  File "/Users/evan/Desktop/ItChat/itchat/components/login.py", line 165, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0


我的Python 版本是 Python 2.7.10

**Comment by HevLfreis** [comment]
确实是python的问题，升级到11,13都正确了
