### ISSUE TITLE
itchat登录失败

### ISSUE THREAD

**Issue by trysh** [littlecodersh/ItChat#402]
同一个微信账号，在手机版、web版都可以正常登录
在itchat登录失败
```python
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trys2163/.local/lib/python3.5/site-packages/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/home/trys2163/.local/lib/python3.5/site-packages/itchat/components/login.py", line 67, in login
    self.show_mobile_login()
  File "/home/trys2163/.local/lib/python3.5/site-packages/itchat/components/login.py", line 213, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'
```

**Comment by codexpage** [comment]
我也遇到了这个问题，一模一样

**Comment by cwhy** [comment]
我也是。。难道api变了？

**Comment by nonva** [comment]
有解决方案么？

**Comment by blueset** [comment]
关于六月份开始频繁掉线及暂时封号的情况，这里有一个小调查：
[Issue #1 Comment 306685858](https://github.com/littlecodersh/ItChat/issues/1#issuecomment-306685858)

**Comment by littlecodersh** [comment]
绑银行卡，微信对新号的限制一直不少

**Comment by trysh** [comment]
@littlecodersh 银行卡很早之前就绑定了，不是信号。
而且，我现在的问题是：在手机版、wx.qq.com都可以正常登录，只是itchat登录失败

**Comment by littlecodersh** [comment]
@trysh 在q群里找我qq号加我一下，我私聊给你修修看

**Comment by trysh** [comment]
@littlecodersh 不好意思啊，我在6月7号早上遇见这个问题，就开始一直尝试，手机、电脑、VPS用同一个IP，用同一个UA，手机注销重登微信账号、VPS卸载重装，均无法登录itchat。
然后我只能干等，等到6月8号晚上，itchat就可以登录了，所以我现在没法重现这个问题了

**Comment by littlecodersh** [comment]
@trysh 好，之后如果还出现这个问题再回复一下这个issue

**Comment by trysh** [comment]
@littlecodersh 好的，辛苦你了，谢谢

**Comment by trysh** [comment]
楼上几个朋友，如果还持续着这个问题，可以联系作者

**Comment by codexpage** [comment]
我隔了三天之后，再次登录发现这个问题也消失了，很奇怪

**Comment by hdyang12** [comment]
我也出现了这个问题，目前还登不上

**Comment by superchaoran** [comment]
@littlecodersh 
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "tiantian.py", line 12, in <module>
    itchat.auto_login(enableCmdQR=2,hotReload=True)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/register.py", line 31, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 67, in login
    self.show_mobile_login()
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 213, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

**Comment by ztczxwzxw** [comment]
我也出现了

**Comment by ztczxwzxw** [comment]
@littlecodersh 我知道怎么出现的了。原来微信号一直登陆A程序，是用itchat.new_instance的。我新写了B程序复制A程序的，忘记改保存的statusStorageDir了，第一次启用之后进不去。然后再改statusStorageDir，就开始报pass_ticket错了。今天被搞断两个号了。紧急求助

**Comment by houdzaiw** [comment]
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Traceback (most recent call last):
  File "login.py", line 184, in <module>
    main()
  File "login.py", line 177, in main
    itchat.auto_login(hotReload=True)
  File "/Users/evan/Desktop/ItChat/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Users/evan/Desktop/ItChat/itchat/components/login.py", line 49, in login
    status = self.check_login()
  File "/Users/evan/Desktop/ItChat/itchat/components/login.py", line 133, in check_login
    if process_login_info(self, r.text):
  File "/Users/evan/Desktop/ItChat/itchat/components/login.py", line 168, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0



我也遇到了同样的问题，出现过几次都是等

**Comment by cakejuju** [comment]
非小号,扫码完后出现该错误提示,登陆**网页微信**也得到下面 message 中一样的 alert 提示。
```python
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error>
 <ret>1203</ret>
 <message>
 Your login may be compromised. For account security, you cannot log in to Web WeChat. You can try mobile WeChat or Windows WeChat.
 </message>
</error>
```
意思是微信检测到我的账号被 hack 了？怎么破？

**Comment by sutra** [comment]
今天我想起来之后再次测试登录 Web WeChat，发现已经恢复了。
从2017年7月27日开始，到今天（很可能早就解封了）我想起来再去测试，约65天。

**Comment by nyartsgnaw** [comment]
我也出现了这个问题，我估计是因为登录bot导致的暂时封号．．
微信那边如何断定bot是不知道的，不过不知道itchat是否模仿了浏览器行为？是不是wechat那边从登录的meta data那里是无法鉴别是否是bot的？
谢谢

**Comment by wishingweed** [comment]
大家用bot是否有多 窗口同时发送消息的使用场景

**Comment by 1e0ndavid** [comment]
Traceback (most recent call last):
  File "/Users/davidleon/Desktop/plan.py", line 30, in <module>
    itchat.auto_login(hotReload=True, enableCmdQR=2,loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Users/davidleon/anaconda3/lib/python3.6/site-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Users/davidleon/anaconda3/lib/python3.6/site-packages/itchat/components/login.py", line 53, in login
    status = self.check_login()
  File "/Users/davidleon/anaconda3/lib/python3.6/site-packages/itchat/components/login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "/Users/davidleon/anaconda3/lib/python3.6/site-packages/itchat/components/login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/Users/davidleon/anaconda3/lib/python3.6/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/Users/davidleon/anaconda3/lib/python3.6/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/Users/davidleon/anaconda3/lib/python3.6/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

请教一下，也出现了类似的问题，请问是因为什么，目前有没有解决的方法呢？

**Comment by medder** [comment]
遇到同样的问题，换个微信号可以登录，估计还是跟微信号有关。


Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>

**Comment by sutra** [comment]
> 今天我想起来之后再次测试登录 Web WeChat，发现已经恢复了。
> 从2017年7月27日开始，到今天（很可能早就解封了）我想起来再去测试，约65天。

上述部署环境为使用位于美国的 VPS，但是我是在上海使用 iOS 版本的微信。

从约 Sep 29, 2018 我改了部署方式，不再使用位于美国的 VPS，而是改为部署在上海，也就是我的 iOS 版本的微信经常登录的同一 IP 的机器上。至今 Nov 3, 2018，约1个月，没有发生被 ban 的情况。

这一次部署所使用的相关软件的版本号：
* efb-telegram-master (2.0.0b12)
* efb-wechat-slave (2.0.0a13)
* itchat (1.3.10)

**Comment by CSFCi** [comment]
怎么解决啊  Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>
Traceback (most recent call last):

**Comment by pkucoco** [comment]
同上，连网页版微信都登陆不上了

**Comment by superchaoran** [comment]
> 同上，连网页版微信都登陆不上了
@pkucoco 
你也是pku的？我有个朋友也是pku的，现在在谷歌。如果对类似的项目感兴趣可以找我聊聊。
我的微信是tiantian20170427

**Comment by pkucoco** [comment]
我是pku信息管理系，现在刚刚大一，很高兴能够认识您！
这个问题的发生状况是：我想利用python对微信群聊记录进行整理，提供一个对微信重要文件自动保存，对群聊人员活跃度进行统计的小程序。
假如不能使用auto_login，可能就要寻求其他途径导出微信聊天记录，但我查阅的方法中，似乎都很麻烦。sigh
很高兴认识你！！

Chaoran Wang <notifications@github.com> 于2019年7月3日周三 上午11:40写道：

**Comment by douym** [comment]
同不能登陆

**Comment by ken0912** [comment]
同样的问题：
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>
Start auto replying.

**Comment by Amos698** [comment]
使用itchat和网页版微信均不能登录，应该是微信做了限制吧

**Comment by sutra** [comment]
> > 今天我想起来之后再次测试登录 Web WeChat，发现已经恢复了。
> > 从2017年7月27日开始，到今天（很可能早就解封了）我想起来再去测试，约65天。
> 
> 上述部署环境为使用位于美国的 VPS，但是我是在上海使用 iOS 版本的微信。
> 
> 从约 Sep 29, 2018 我改了部署方式，不再使用位于美国的 VPS，而是改为部署在上海，也就是我的 iOS 版本的微信经常登录的同一 IP 的机器上。至今 Nov 3, 2018，约1个月，没有发生被 ban 的情况。
> 
> 这一次部署所使用的相关软件的版本号：
> 
> * efb-telegram-master (2.0.0b12)
> * efb-wechat-slave (2.0.0a13)
> * itchat (1.3.10)

从 2018-09-29 至  2020-07-07，部署环境均为上海家用电信网络（微信直连，Telegram 使用运行在整个路由器上的特殊机制来连接），已经稳定运行了1年零10个月，没有出现任何问题。

今天，2020-07-07 我将我的运行 EFB 的 FreeBSD jail 从家用电信宽带迁移到阿里云杭州（微信直连，Telegram 使用 socks5 联入原来的特殊网络）。
