### ISSUE TITLE
SSL证书验证失败

### ISSUE THREAD

**Issue by virgilliu** [littlecodersh/ItChat#414]
登录的时候就报ssl证书验证失败

>>> itchat.auto_login()
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Python34\lib\site-packages\urllib3\util\ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python34\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\Python34\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\Python34\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 630, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\itchat\utils.py", line 125, in test_connect
    r = requests.get(config.BASE_URL)
  File "C:\Python34\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python34\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

You can't get access to internet or wechat domain, so exit.

**Comment by silencesdg** [comment]
我也有这个问题 你解决了么

**Comment by virgilliu** [comment]
File "C:\Python34\lib\site-packages\itchat\utils.py", line 125, in test_connect
r = requests.get(config.BASE_URL)
这里稍微修改一下：
r = requests.get(config.BASE_URL，verify=False)

还有几个类似的地方需要修改

**Comment by csbs** [comment]
SSL 证书校验阶段失败
直接在机器上使用
requests.get( ，certi = )  指定证书，一般是证书问题
使用的证书文件一般在 xxxx/site-packages/certifi-py2.7.egg/certifi/ 这个地方

**Comment by zr000** [comment]
a或者b可以解决
a、import ssl
ssl._create_default_https_context = ssl._create_unverified_context
b、/etc/python/cert-verification.cfg
verify=disable
