### ISSUE TITLE
ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))

### ISSUE THREAD

**Issue by winneryong** [littlecodersh/ItChat#424]
```
Request to send a text message to @ac4f6af99451c5cccc0fcc92faee848da2faf92c1e3ac26d1ebe398d58d1d11a: Text: [发怒][发怒][发怒]
Traceback (most recent call last):
  File "build/bdist.macosx-10.11-intel/egg/itchat/components/login.py", line 232, in maintain_loop
    i = sync_check(self)
  File "build/bdist.macosx-10.11-intel/egg/itchat/components/login.py", line 285, in sync_check
    r = self.s.get(url, params=params, headers=headers, timeout=config.TIMEOUT)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))

Request to send a text message to @ac4f6af99451c5cccc0fcc92faee848da2faf92c1e3ac26d1ebe398d58d1d11a: Text: [流泪]
```

itchat版本为：`1.3.7`。
回复几个消息后就出现上面的异常，不过程序可以继续运行，可以正常回复消息。

**Comment by pengyuwei** [comment]
我也经常出这个错误，而且出完之后，就再也不能收发消息了

**Comment by littlecodersh** [comment]
@winneryong @pengyuwei 登陆后的操作被服务器拒绝了，网络稳定的话建议发送信息也限制一下频率。

**Comment by zsdonghao** [comment]
@littlecodersh 你好～ 我遇到的情况是，当对方在打字（还没发送），我这边就会断开。  这会是什么原因造成的呢？网络环境是很快的，在macbook pro上跑的。
