### ISSUE TITLE
按照说明下载了fields.py，为啥包含中文字符的文档还是无法上传

### ISSUE THREAD

**Issue by lily1982** [littlecodersh/ItChat#428]
您好，在上传含有中文字符的文档时，按照说明下载了fields.py文件，但是为啥还是报错啊，python版本是2.7，itchat的版本是1.3.7，谢谢！

**Comment by cswxin** [comment]
我也一样，版本也是2.7+1.3.7

**Comment by lily1982** [comment]
@littlecodersh,您好，在不？上传含有中文字符的文档时，下载了fields.py,为啥还是报错啊，python版本是2.7，itchat的版本是1.3.7，谢谢！

**Comment by littlecodersh** [comment]
@lily1982 把报错内容贴一下吧。

**Comment by lily1982** [comment]
@littlecodersh 报错信息如下：
Traceback (most recent call last):
  File "D:\message1.py", line 47, in <module>
    chatrooms[0].send_file(r'd:/测试.txt')
  File "C:\Python27\ArcGIS10.1\lib\site-packages\itchat\storage\templates.py", line 114, in send_file
    return self.core.send_file(fileDir, self.userName, mediaId)
  File "C:\Python27\ArcGIS10.1\lib\site-packages\itchat\components\messages.py", line 366, in send_file
    mediaId, toUserName, fileDir))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 3: ordinal not in range(128)

**Comment by lily1982** [comment]
@littlecodersh 报错信息如下：
Traceback (most recent call last):
File "D:\message1.py", line 47, in 
chatrooms[0].send_file(r'd:/测试.txt')
File "C:\Python27\ArcGIS10.1\lib\site-packages\itchat\storage\templates.py", line 114, in send_file
return self.core.send_file(fileDir, self.userName, mediaId)
File "C:\Python27\ArcGIS10.1\lib\site-packages\itchat\components\messages.py", line 366, in send_file
mediaId, toUserName, fileDir))

**Comment by MayerYang** [comment]
编码冲突了，试一下添加如下代码：
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

**Comment by littlecodersh** [comment]
@lily1982 
```python
u'd:/测试.txt'
```
