### ISSUE TITLE
ConnectionError login.py 232

### ISSUE THREAD

**Issue by rongwwei** [littlecodersh/ItChat#432]
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/itchat/components/login.py", line 232, in maintain_loop
     i = sync_check(self)
   File "/usr/lib/python2.7/site-packages/itchat/components/login.py", line 287, in sync_check
    r = self.s.get(url, params=params, headers=headers, timeout=config.TIMEOUT)
   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
     return self.request('GET', url, **kwargs)
   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
     r = adapter.send(request, **kwargs)
   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 453, in send
     raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\\r\\n',))

我这个自定义的登录过程：
在确认check_login的status是200后，我运行如下代码：
        wx.web_init();
        wx.show_mobile_login();
        wx.get_friends(True);
        wx.get_contact(True);
        wx.start_receiving();

然后在dump_login_status之后就结束了线程

然后在几秒后再用load_login_status再重新获得之前的对象

然后问题是：有时可以正常发送，有时不可以

日志有很多第一行贴出来的错误
感觉是不是和其他童鞋的213行的错误差不多？不太确定，来确定下，如果是我的代码有问题，希望各位大大指正

**Comment by seedds** [comment]
同样遇到这个问题

**Comment by littlecodersh** [comment]
@rongwwei 已在1.3.9中修复该问题。
