### ISSUE TITLE
扫描二维码后不能登录

### ISSUE THREAD

**Issue by yudun1989** [littlecodersh/ItChat#436]
```
Please press confirm on your phone.
Traceback (most recent call last):
  File "m/utils/itbot.py", line 134, in <module>
    itchat.auto_login(enableCmdQR=2, hotReload=True)
  File "/home/ubuntu/miniconda2/envs/fuping/lib/python2.7/site-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/home/ubuntu/miniconda2/envs/fuping/lib/python2.7/site-packages/itchat/components/login.py", line 49, in login
    status = self.check_login()
  File "/home/ubuntu/miniconda2/envs/fuping/lib/python2.7/site-packages/itchat/components/login.py", line 133, in check_login
    if process_login_info(self, r.text):
  File "/home/ubuntu/miniconda2/envs/fuping/lib/python2.7/site-packages/itchat/components/login.py", line 168, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/home/ubuntu/miniconda2/envs/fuping/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/home/ubuntu/miniconda2/envs/fuping/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/home/ubuntu/miniconda2/envs/fuping/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-54: ordinal not in range(128)
```

您的itchat版本为：`itchat-1.3.8-py2.py3-none-any.whl`。

其他的内容或者问题更详细的描述都可以添加在下面：

> 扫描之后不能登录

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by yudun1989** [comment]
<error><ret>1203</ret><message>当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。</message></error>

账号有问题应该是。
