### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by Crayon277** [littlecodersh/ItChat#438]
应该是卡在了`itchat.auto_login()`这一步。完整的报错是：
```
Getting uuid of QR code.
Traceback (most recent call last):
  File "open_door.py", line 10, in <module>
    itchat.auto_login()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/itchat/components/login.py", line 41, in login
    while not self.get_QRuuid():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/itchat/components/login.py", line 98, in get_QRuuid
    r = self.s.get(url, params=params, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: /jslogin?fun=new&appid=wx782c26e4c19acffb (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1025964d0>: Failed to establish a new connection: [Errno 60] Operation timed out',))
```

**Comment by muxiong0308** [comment]
装python3就行




发自网易邮箱大师
在2017年06月30日 20:09，MMMMMCCLXXVII 写道：

应该是卡在了itchat.auto_login()这一步。完整的报错是：

Getting uuid of QR code.
Traceback (most recent call last):
  File "open_door.py", line 10, in <module>
    itchat.auto_login()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/itchat/components/login.py", line 41, in login
    while not self.get_QRuuid():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/itchat/components/login.py", line 98, in get_QRuuid
    r = self.s.get(url, params=params, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: /jslogin?fun=new&appid=wx782c26e4c19acffb (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1025964d0>: Failed to establish a new connection: [Errno 60] Operation timed out',))
