### ISSUE TITLE
这个错误怎么解决呢？AttributeError: 'module' object has no attribute 'ReadTimeout'

### ISSUE THREAD

**Issue by lpx1520** [littlecodersh/ItChat#442]
使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 263, in maintain_loop
    except requests.exceptions.ReadTimeout:
AttributeError: 'module' object has no attribute 'ReadTimeout'

itchat版本为：
>>> print(itchat.__version__)
1.3.8

**Comment by littlecodersh** [comment]
@lpx1520 升级一下requests版本吧，目前最新的版本应该是2.18.1
```bash
python -m pip install requests -U
```
