### ISSUE TITLE
读取朋友圈数据失败

### ISSUE THREAD

**Issue by gaoren2017** [littlecodersh/ItChat#443]
[求助] 用itchat读取微信朋友信息的时候，碰到error，求圈友解答下，代码就几段

```python
#coding:utf-8
import itchat
# 先登录
itchat.login()
# 获取好友列表
friends = itchat.get_friends(update=True)[0:]
```

但错误如何下

```python
import itchat

itchat.login()
# 获取好友列表
itchat has already logged in.

friends = itchat.get_friends(update=True)[0:]
Traceback (most recent call last):

  File "<ipython-input-23-a3bc73662132>", line 1, in <module>
    friends = itchat.get_friends(update=True)[0:]

  File "C:\ProgramData\Anaconda3\lib\site-packages\itchat\components\contact.py", line 306, in get_friends
    self.get_contact(update=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\itchat\components\contact.py", line 285, in get_contact
    seq, batchMemberList = _get_contact(seq)

  File "C:\ProgramData\Anaconda3\lib\site-packages\itchat\components\contact.py", line 269, in _get_contact
    url = '%s/webwxgetcontact?r=%s&seq=%s&skey=%s' % (self.loginInfo['url'],

KeyError: 'url'
```

**Comment by littlecodersh** [comment]
@gaoren2017 显示来说是你已经登录过一遍了，完整程序就是这样吗？

**Comment by advpetc** [comment]
可以使用itchat.auto_login(hotReload=True)来重复登录
