### ISSUE TITLE
我把代码上传到GAE(google app engine)，运行、出现下面的错误 本地都可以

### ISSUE THREAD

**Issue by GhostClock** [littlecodersh/ItChat#444]
```
xxxxxx@ultra-mason-127914:~/WeChat$ python demo01.py 
Getting uuid of QR code.
Downloading QR code.
Traceback (most recent call last):
  File "demo01.py", line 80, in <module>
    itchat.auto_login()
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 45, in login
    picDir=picDir, qrCallback=qrCallback)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 119, in get_QR
    utils.print_qr(picDir)
  File "/usr/local/lib/python2.7/dist-packages/itchat/utils.py", line 83, in print_qr
    subprocess.call(['xdg-open', fileDir])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by littlecodersh** [comment]
@GhostClock GAE没有安装xdg-open，你需要别的二维码开启方法。

**Comment by GhostClock** [comment]
我在GAE上安装了xdg-open，然后用“启动代码编辑器”功能扫描的二维码，这样可以
