### ISSUE TITLE
对方正在输入时，程序出现bug

### ISSUE THREAD

**Issue by heuxx** [littlecodersh/ItChat#446]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

Login successfully as xx
Start auto replying.
No uins in 51 message

```
[在这里粘贴完整日志]

No uins in 51 message

Request to send a text message to @a0bdddbcf746151673aa668584cc7c9974398de775da6
18fb5a7f97c7711611a: dd
Traceback (most recent call last):
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\http\client
.py", line 1197, in getresponse
    response.begin()
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\http\client
.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\http\client
.py", line 285, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: HTTP/1.1 0 -


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\http\client
.py", line 1197, in getresponse
    response.begin()
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\http\client
.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\http\client
.py", line 285, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('HTTP/1.
1 0 -\r\n',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\itchat\components\login.py", line 240, in maintain_loop
    i = sync_check(self)
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\itchat\components\login.py", line 295, in sync_check
    r = self.s.get(url, params=params, headers=headers, timeout=config.TIMEOUT)
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\requests\sessions.py", line 526, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\requests\sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\requests\sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\xuxin\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('HTTP
/1.1 0 -\r\n',))


您的itchat版本为：1.3.8。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> 我的代码如下：
# -*- coding: utf-8 -*-
import itchat

@itchat.msg_register(itchat.content.TEXT)
def text_reply(msg):
	return msg['Text']

itchat.auto_login(hotReload = True,enableCmdQR=True)
itchat.run(debug=True)

登录后，和好友聊天时，当我手机上显示 “对方正在输入.....”时，出现上述错误！

[document]: https://github.com/soimort/you-get/wiki/FAQ
[issues]: https://github.com/soimort/you-get/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by aijisud** [comment]
很容易就复现了。怀疑是itchat处理“对方正在输入...”时，把它当作了一条消息，就出错了。

**Comment by shuizuo** [comment]
我用的itchat 版本也是1.3.8 复现‘No uins in 51 message’报错，是通过在手机上点开好友聊天界面的瞬间，出现该报错。不但如此，点开微信公众号和文件传输助手等均会出现该报错

**Comment by littlecodersh** [comment]
@heuxx 已在新版本1.3.9中修复该问题。

**Comment by minning** [comment]
修复了吗，我的itchat 1.3.10 版本还有这个问题

**Comment by Chesterguan** [comment]
我也出现了这个问题

**Comment by hansenma** [comment]
有解决方案吗？
