### ISSUE TITLE
更新到最新版本后出现的问题，好像和超时的错误处理有关

### ISSUE THREAD

**Issue by gaozhaosg** [littlecodersh/ItChat#470]
在提交前，请确保您已经检查了以下内容!

- [ Y ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ Y ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ Y ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ Y ] 本问题确实关于`itchat`, 而不是其他项目.
- [ Y ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ec2-user/html/itchat/components/login.py", line 267, in maintain_loop
    except requests.exceptions.ReadTimeout:
AttributeError: 'module' object has no attribute 'ReadTimeout'

您的itchat版本为：`[1.3.9]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [近期经常出这个错误，看信息像是超时的错误控制，但是不知道应该如何处理]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by gaozhaosg** [comment]
我在一个全新的目录重新git clone了最新版本(1.3.9)的代码，然后使用文档说明里的demo 代码，仍然是同样的错误。机器是电信机房的服务器，接入主干网，网速不应该有任何问题，之前也一直跑得挺顺利的。

**Comment by gaozhaosg** [comment]
重新换回v1.3.7的代码，这个问题就不再重新

**Comment by littlecodersh** [comment]
@gaozhaosg 更新一下requests

```python
python -m pip install requests -U
```
