### ISSUE TITLE
You can't get access to internet or wechat domain, so exit.

### ISSUE THREAD

**Issue by liangchen815** [littlecodersh/ItChat#487]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\itchat\utils.py", line 125, in test_connect
    r = requests.get(config.BASE_URL)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

You can't get access to internet or wechat domain, so exit.
An exception has occurred, use %tb to see the full traceback.

SystemExit

**Comment by littlecodersh** [comment]
@liangchen815 ssl的连接问题，建议用requests获取https网站进行debug。
