### ISSUE TITLE
获取二维码链接有问题

### ISSUE THREAD

**Issue by shuniversity** [littlecodersh/ItChat#490]
在get_QR函数中获取二维码qrCode = QRCode('https://login.weixin.qq.com/l/' + uuid)，其中url应该为： 
qrCode = QRCode('https://login.weixin.qq.com/qrcode' + uuid)

**Comment by Chyroc** [comment]
`os.path.join('https://login.weixin.qq.com/qrcode', uuid)`更好吧

**Comment by Chyroc** [comment]
@shuniversity 能否贴出错误截图？还有电脑系统+手机系统？非常感谢

**Comment by qiu-xm** [comment]
`>>> import itchat
>>> itchat.auto_login()
Getting uuid of QR code.
Downloading QR code.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 49, in login
    picDir=picDir, qrCallback=qrCallback)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 123, in get_QR
    utils.print_qr(picDir)
  File "/usr/local/lib/python2.7/dist-packages/itchat/utils.py", line 83, in print_qr
    subprocess.call(['xdg-open', fileDir])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by qiu-xm** [comment]
用不起来，是我python(2.7.6) 版本太低了吗？
脚本所在文件夹生成了QR.png，下载打开后微信扫了之后可以登录

`
Getting uuid of QR code.
Downloading QR code.
Error: no "view" rule for type "image/png" passed its test case
       (for more information, add "--debug=1" on the command line)
Can't call method "get_value" on an undefined value at /usr/bin/mimeopen line 162.
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: lynx: not found
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as xxxx
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 267, in maintain_loop
    except requests.exceptions.ReadTimeout:
AttributeError: 'module' object has no attribute 'ReadTimeout'

Start auto replying.
`

**Comment by littlecodersh** [comment]
@shuniversity 二维码链接的确更新了，多谢提醒！

**Comment by littlecodersh** [comment]
@qiu-xm 把requests更新一下
```bash
python -m pip install requests -U
```
另外用命令行输出二维码
```python
itchat.auto_login(enableCmdQR=True)
```
