### ISSUE TITLE
扫描二维码后程序崩溃

### ISSUE THREAD

**Issue by qiu-xm** [littlecodersh/ItChat#493]
昨天还好好的，今天突然不能用了
```
D:\python>python chat.py
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Traceback (most recent call last):
  File "chat.py", line 184, in <module>
    itchat.auto_login(True)
  File "C:\Python27\lib\site-packages\itchat\components\register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "C:\Python27\lib\site-packages\itchat\components\login.py", line 53, in login
    status = self.check_login()
  File "C:\Python27\lib\site-packages\itchat\components\login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "C:\Python27\lib\site-packages\itchat\components\login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "C:\Python27\lib\xml\dom\minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

**Comment by qiu-xm** [comment]
其他报错
```
Traceback (most recent call last):
  File "chat.py", line 184, in <module>
    itchat.auto_login(True)
  File "C:\Python27\lib\site-packages\itchat\components\register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "C:\Python27\lib\site-packages\itchat\components\login.py", line 53, in login
    status = self.check_login()
  File "C:\Python27\lib\site-packages\itchat\components\login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "C:\Python27\lib\site-packages\itchat\components\login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "C:\Python27\lib\xml\dom\minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-54: ordinal not in range(128)
```

**Comment by xiaoliuwayne** [comment]
今天我也遇到同样的问题了，请问你解决了吗

**Comment by xiaoliuwayne** [comment]
我卸载itchat 再重装，发现 是微信号被限制登陆网页版了
