### ISSUE TITLE
AttributeError: 'WeChat' object has no attribute 'newInstance'

### ISSUE THREAD

**Issue by haoshasha** [littlecodersh/ItChat#507]
```
import threading
import itchat

class WeChat(threading.Thread):

    def __int__(self):
        threading.Thread.__init__(self)
        self.newInstance = itchat.new_instance()

    def run(self):
        self.newInstance.auto_login(hotReload=True, statusStorageDir='newInstance.pkl')
        self.newInstance.run()

if __name__ == '__main__':
    wx = WeChat()
    wx.start() 

so, this is my code, the error is 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/shasha/Desktop/飞天/manager/wechat.py", line 11, in run
    self.newInstance.auto_login(hotReload=True, statusStorageDir='newInstance.pkl')
AttributeError: 'WeChat' object has no attribute 'newInstance'

so, this is why???
```

**Comment by littlecodersh** [comment]
@haoshasha 
```python
def __init__(self)
```
