### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-60: ordinal not in range(128)

### ISSUE THREAD

**Issue by nhmice** [littlecodersh/ItChat#525]
测试环境:python2.7
安装方法:pip install itchat
测试代码：
```python
#coding=utf-8
import itchat, time
@itchat.msg_register(itchat.content.TEXT)
def text_reply(msg):
    return msg.text

itchat.auto_login(True)
itchat.run(debug=True)
```

运行时cmd输出信息：
```bash
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    itchat.auto_login()
  File "/Users/Tenya/Temp/python_test/ItChat/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Users/Tenya/Temp/python_test/ItChat/itchat/components/login.py", line 53, in login
    status = self.check_login()
  File "/Users/Tenya/Temp/python_test/ItChat/itchat/components/login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "/Users/Tenya/Temp/python_test/ItChat/itchat/components/login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-60: ordinal not in range(128)
```

请问这个unicodeEncodeError是怎样导致的？如何解决

**Comment by ZhangQian-Cheryl** [comment]
我的情况是这样的，新注册的账号不能登录网页版，所以扫码登录的时候会返回提示，应该是这个提示导致的unicodeEncodeError的

**Comment by 70kg** [comment]
注册多久的算新注册的？  我的帐号都好几个月了还是不行 @ZhangQian-Cheryl

**Comment by ZhangQian-Cheryl** [comment]
@70kg  不知道诶，你可以用你的账号登录下网页版微信看看，如果网页版微信都不能登录，那itchat也是登录不了的。

**Comment by yolandazcc** [comment]
我也遇到了。登陆成功后运行1~2天掉线，再次登陆就失败，报以上错误

**Comment by NullYing** [comment]
itchat捕获错误信息有问题，尤其是封号信息

**Comment by littlecodersh** [comment]
@nhmice 账号是否仍存在该问题？可以邮件联系我，我看一下是否能够获取登录异常的提示。
