### ISSUE TITLE
send_image在for循环中第二次发送出错，提示链接重置

### ISSUE THREAD

**Issue by lfrdreamman** [littlecodersh/ItChat#545]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/itchat/components/login.py", line 250, in maintain_loop
    msgList, contactList = self.get_msg()
  File "/usr/lib/python2.7/site-packages/itchat/components/login.py", line 332, in get_msg
    r = self.s.post(url, data=json.dumps(data), headers=headers, timeout=config.TIMEOUT)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))
```

您的itchat版本为：`1.3.9`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> 在for 循环里发送图片send_image 提示上面的错误

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by littlecodersh** [comment]
@lfrdreamman 看代码是由于发送过快导致后台整体拒绝了连接。
报错的是保持与后台连接的方法`get_msg`，也就是图片其实已经完成了上传，但是后台采取了拒绝。
