### ISSUE TITLE
 嵌套函数中的return 会报错

### ISSUE THREAD

**Issue by yangxuan8282** [littlecodersh/ItChat#56]
函数结构类似：

```python
def function(self):
	def function1(self):
		url = 
		r = requests.get(url + ak + '&addr=' + self)
		hjson = r.json()
		if hjson["code"] == 0:
			return r.text
		else:
			return u'error'
	return function1
```

报错内容：

```shell
Traceback (most recent call last):
  File "map_flat.py", line 115, in <module>
    itchat.run()
  File "/home/alarm/repos/map_flat/itchat/__init__.py", line 82, in run
    configured_reply()
  File "/home/alarm/repos/map_flat/itchat/__init__.py", line 60, in configured_reply
    if replyFn: send(replyFn(msg), msg.get('FromUserName'))
  File "/home/alarm/repos/map_flat/itchat/__init__.py", line 41, in send
    if msg[:5] == '@fil@':
TypeError: 'function' object has no attribute '__getitem__'
```

**Comment by littlecodersh** [comment]
@yangxuan8282 把实际的代码贴上来吧，只是个类似就算我想也没办法给你debug的

**Comment by yangxuan8282** [comment]
```python
#!/usr/bin/env python
#coding=utf-8

import os
import sys
import itchat
import time
import requests
import json 

help = '''\
map flat:
* 输入应为地址，
* 如 `中关村SOHO`，`回龙观`
* help(show this message)\
'''

ak = 'NDZkMzA2ZDdlYTI3NDBjZjhjZGRiM2MzMWQ4M2I0NTY'

@itchat.msg_register('Text')
def get_dest(msg):
	# comment next line if you can't send message to yourself
	# if not msg['FromUserName'] == msg['ToUserName']: return
	if msg['Text'] in ['help', u'帮助']:
		return help
	else:
		destination = msg.get('Content', '')
		try:
			return search_area(destination)
		except:
			return u'未查询到结果'


def search_area(destination):

	def geocode(self):
		url = 'http://geohey.com/s/geocoding/geocode?ak='
		r = requests.get(url + ak + '&addr=' + self)
		hjson = r.json()
		if hjson["code"] == 0:
			# return r.text
			public_time(hjson)
		else:
			return u'未找到地址'

	def public_time(hjson):
		url = 'http://geohey.com/s/routing/publictime?ak='
		location = [hjson["data"][0]["x"],hjson["data"][0]["y"]]
		location = str(location)
		r = requests.get(url + ak + '&loc=' + location + '&time=30')
		hjson = r.json()
		if hjson["code"] == 0:
			# print r.text
			return r.status_code  
			# convex_hull(hjson)
		else:
			return u'生成公交等时圈出现错误'
	
	geocode(destination)
	return public_time # 如果返回成功应该返回 200
	# return geocode(destination) # 这种方式可以返回geocode，但public_time无法使用此种方式


itchat.auto_login()
itchat.run()

**Comment by littlecodersh** [comment]
search_area方法返回的是一个方法而不是字符串

**Comment by yangxuan8282** [comment]
@littlecodersh 那怎么才能把 `public_time` 里的 `r.status_code` 返回到微信上呢

**Comment by littlecodersh** [comment]
@yangxuan8282 向search_area方法传入需要的hjson值，假设hjson值已定义：
```python
return public_time(hjson)
```

**Comment by yangxuan8282** [comment]
@littlecodersh 这种方法确实可以，之前测试 `public_time` 返回值的时候就是这么做的
但具体到 `public_time` 中的 `hjson` 似乎不适用，它是从 `geocode` 传递过来的

**Comment by littlecodersh** [comment]
@yangxuan8282 程序结构你再调整吧

**Comment by littlecodersh** [comment]
@yangxuan8282 python基础相关的问题建议加一些python的群进行交流
