### ISSUE TITLE
扫描生成的二维码，但是没有反应

### ISSUE THREAD

**Issue by yushidan** [littlecodersh/ItChat#588]
今天第一次研究itchat，根据document中的描述，enableCmdQR=2并运行代码之后能够生成完整的二维码，但是用手机微信扫描后却没有任何反应。

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
网页版微信登录正常
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
已阅读
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
没有找到
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
是的
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

扫描二维码时没有任何报错，但是程序停止后有如下错误，不确定哪些与扫描二维码有关。
```bash
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shidanyu/PycharmProjects/wechatRobort/init.py", line 30, in <module>
    itchat.auto_login(enableCmdQR=2,hotReload=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/itchat/components/login.py", line 53, in login
    status = self.check_login()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/itchat/components/login.py", line 133, in check_login
    r = self.s.get(url, params=params, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 280, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1624, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
KeyboardInterrupt
```

您的itchat版本为：1.3.10

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by jackyrong** [comment]
我的也是无任何反映，用的PYTHON3

**Comment by archie-yu** [comment]
应该是显示问题，移动手机摄像头有时候能扫出来，但是我扫描后会提示登录超时，导致二维码刷新。

**Comment by littlecodersh** [comment]
@yushidan 看上去是网络连接问题，然后你^C取消。
确认一下如果用浏览器登陆是否可行。
