### ISSUE TITLE
itchat.login(),报错提示无法找到指定路径

### ISSUE THREAD

**Issue by echochenyueyang** [littlecodersh/ItChat#625]
在提交前，请确保您已经检查了以下内容!

- [ N ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ Y ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ Y ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ Y ] 本问题确实关于`itchat`, 而不是其他项目.
- [ Y ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
>>> itchat.run(debug=True)
Start auto replying.
>>> 

```

您的itchat版本为：'[1.3.10]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

提示没有指定路径，怀疑是找不到QR.png,但是没有找到具体原因

>>> import itchat
>>> itchat.login()
Getting uuid of QR code.
/usr/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Downloading QR code.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "itchat/components/login.py", line 49, in login
    picDir=picDir, qrCallback=qrCallback)
  File "itchat/components/login.py", line 123, in get_QR
    utils.print_qr(picDir)
  File "itchat/utils.py", line 88, in print_qr
    subprocess.call(['xdg-open', fileDir])
  File "/usr/local/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1228, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
>>> 

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by long2icc** [comment]
我也是这个错，系统信息如下：
CentOS release 6.8 (Final)
Python 2.7.10

**Comment by xianqiangzhao** [comment]
我也报错 
Python 2.7.5
centos 7 64bit

**Comment by xianqiangzhao** [comment]
解决了
用 itchat.auto_login(enableCmdQR=2)
不用itchat.auto_login() 即可解决

**Comment by Vickey-Wu** [comment]
现在扫码登录不了了，扫描登录后报错
```
Please scan the QR code to log in.
Please press confirm on your phone.
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>To protect your account, logging in to WeChat via the web has been suspended. Use WeChat for Windows or WeChat for Mac to log in on a computer. Download WeChat for Windows or Mac at http://wechat.com.</message></error>
```
