### ISSUE TITLE
使用get_friends()获取所有好友时，出现错误

### ISSUE THREAD

**Issue by kskgy** [littlecodersh/ItChat#630]
使用的itchat版本为：`1.3.10`，微信好友数量：3000+。

```
Traceback (most recent call last):
  File "wechat.py", line 19, in <module>
    login()
  File "wechat.py", line 4, in login
    itchat.auto_login(loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Users/ks/anaconda3/lib/python3.6/site-packages/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Users/ks/anaconda3/lib/python3.6/site-packages/itchat/components/login.py", line 73, in login
    self.get_contact(True)
  File "/Users/ks/anaconda3/lib/python3.6/site-packages/itchat/components/contact.py", line 285, in get_contact
    seq, batchMemberList = _get_contact(seq)
  File "/Users/ks/anaconda3/lib/python3.6/site-packages/itchat/components/contact.py", line 281, in _get_contact
    j = json.loads(r.content.decode('utf-8', 'replace'))
  File "/Users/ks/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/ks/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/ks/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by nikingstore** [comment]
源码要贴一贴啊...

**Comment by AutoInfor** [comment]
这个问题我也遇到了，经查看是因为返回的r.content里面包含了多个字典而不是仅仅一个字典

**Comment by anggiluo** [comment]
我也发现了这个问题，不知道有没有什么解决方法。谢谢。
