### ISSUE TITLE
如何获取微信好友的语音消息

### ISSUE THREAD

**Issue by PeterNiuNiu** [littlecodersh/ItChat#646]
你好，大神，我所面临的业务场景是这样的，需要获取好友的语音，
代码是这样的：
```
import itchat
@itchat.msg_register(itchat.content.RECORDING)
def print_content(msg):
    print(msg['Recording'])
itchat.auto_login()
itchat.run()
```
报错信息是这样的：
```
D:\Python36\python.exe D:/PycharmProjects/wechat_auto_msg/test.py
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as on the way
Start auto replying.
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\itchat\components\register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "D:/PycharmProjects/wechat_auto_msg/test.py", line 9, in print_content
  File "D:\Python36\lib\site-packages\itchat\storage\messagequeue.py", line 26, in __getitem__
    return super(Message, self).__getitem__(value)
KeyError: 'Recording'
```

希望得到您的指导，非常感谢

**Comment by ghost** [comment]
itchat.auto_login()
改为
  itchat.auto_login(enableCmdQR=True)
