### ISSUE TITLE
linux系统运行程序后一直出现如下错误

### ISSUE THREAD

**Issue by 282144757** [littlecodersh/ItChat#654]
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    itchat.auto_login(picDir='/opt/QR.png')
  File "/application/python/lib/python3.7/site-packages/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/application/python/lib/python3.7/site-packages/itchat/components/login.py", line 49, in login
    picDir=picDir, qrCallback=qrCallback)
  File "/application/python/lib/python3.7/site-packages/itchat/components/login.py", line 114, in get_QR
    qrCode.png(qrStorage, scale=10)
  File "/application/python/lib/python3.7/site-packages/pyqrcode/__init__.py", line 463, in png
    module_color, background, quiet_zone)
  File "/application/python/lib/python3.7/site-packages/pyqrcode/builder.py", line 1266, in _png
    import png
  File "/application/python/lib/python3.7/site-packages/png.py", line 1919
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

**Comment by zhourunlai** [comment]
`except ValueError as e:`
