### ISSUE TITLE
process_login_info error

### ISSUE THREAD

**Issue by Qiu800820** [littlecodersh/ItChat#659]
login.py:147 core.s.get(core.loginInfo['url'], headers=headers, allow_redirects=False)
没有fun等参数 导致返回结果为空，xml解析报错
![image](https://user-images.githubusercontent.com/7494629/39975976-0ab341e2-5764-11e8-8063-91c1afaa0031.png)

```
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Lucky/Bot/main.py", line 7, in <module>
    run()
  File "C:\Users\Administrator\PycharmProjects\Lucky\Bot\core\core.py", line 171, in run
    itchat.auto_login(hotReload=True)
  File "D:\Python\3.5\lib\site-packages\itchat\components\register.py", line 30, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "D:\Python\3.5\lib\site-packages\itchat\components\login.py", line 48, in login
    status = self.check_login()
  File "D:\Python\3.5\lib\site-packages\itchat\components\login.py", line 131, in check_login
    process_login_info(self, r.text)
  File "D:\Python\3.5\lib\site-packages\itchat\components\login.py", line 164, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "D:\Python\3.5\lib\xml\dom\minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "D:\Python\3.5\lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "D:\Python\3.5\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

**Comment by Qiu800820** [comment]
账号异常  不能登陆web端
