### ISSUE TITLE
get_contact出错

### ISSUE THREAD

**Issue by Frankleee** [littlecodersh/ItChat#670]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
import itchat
itchat.auto_login(hotReload=False)
itchat.run(debug=True)
█
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "D:\python27\lib\site-packages\itchat\components\register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "D:\python27\lib\site-packages\itchat\components\login.py", line 73, in login
    self.get_contact(True)
  File "D:\python27\lib\site-packages\itchat\components\contact.py", line 285, in get_contact
    seq, batchMemberList = _get_contact(seq)
  File "D:\python27\lib\site-packages\itchat\components\contact.py", line 281, in _get_contact
    j = json.loads(r.content.decode('utf-8', 'replace'))
  File "D:\python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")

```

您的itchat版本为：`[1.3.9]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> 网页端**确认可以登录**，用itchat应该是在_get_contact函数中用get获取通讯录出错。
> 这可能和账户有关，我此前用这个账号登录itchat保持一个月以上登录状态，可能tx对账户信息进行了管制？但是网页端可以正常登录，所以说明至少模拟登陆和官方还是有不一致的地方。

```python
    def _get_contact(seq=0):
        url = '%s/webwxgetcontact?r=%s&seq=%s&skey=%s' % (self.loginInfo['url'],
            int(time.time()), seq, self.loginInfo['skey'])
        headers = {
            'ContentType': 'application/json; charset=UTF-8',
            'User-Agent' : config.USER_AGENT, }
        try:
            r = self.s.get(url, headers=headers) //此处获取不到数据
```
![error](https://user-images.githubusercontent.com/10584492/40571808-036d5fd6-60d2-11e8-828c-2452389a3b1c.PNG)

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by binqiangsun** [comment]
解决了么？ 我也碰到这个问题

**Comment by wwppxx878787** [comment]
这个问题有结论了嘛？我也遇到了，有时候有有时候 没有，很奇怪。
