### ISSUE TITLE
出现无法登录的情况

### ISSUE THREAD

**Issue by xigaohu** [littlecodersh/ItChat#671]
在提交前，请确保您已经检查了以下内容!

- [x ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ x] 本问题确实关于`itchat`, 而不是其他项目.
- [x ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Traceback (most recent call last):
  File "C:\Users\gao\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\181.4668.75\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Users\gao\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\181.4668.75\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\gao\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\181.4668.75\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/gao/Desktop/python/wx_robot/auto_reply_chatroom.py", line 103, in <module>
    itchat.auto_login(hotReload=True)#,enableCmdQR=2)
  File "C:\Users\gao\.virtualenvs\wx_robot-DSs4Hzcm\lib\site-packages\itchat\components\register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "C:\Users\gao\.virtualenvs\wx_robot-DSs4Hzcm\lib\site-packages\itchat\components\login.py", line 53, in login
    status = self.check_login()
  File "C:\Users\gao\.virtualenvs\wx_robot-DSs4Hzcm\lib\site-packages\itchat\components\login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "C:\Users\gao\.virtualenvs\wx_robot-DSs4Hzcm\lib\site-packages\itchat\components\login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "c:\python27\Lib\xml\dom\minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "c:\python27\Lib\xml\dom\expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "c:\python27\Lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

您的itchat版本为：`[1.3.10]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> 现在无法登录了.登录时候就报了错误，使用微信的网页版登录是正常的。试了两个号，都是这样的情况。

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by dushanchen** [comment]
网页上也登不了了，**_为了保障你的帐号安全,暂不支持使用网页版微信。你可以前往微信官网 https://weix_**
