### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-54: ordinal not in range(128)

### ISSUE THREAD

**Issue by changtj** [littlecodersh/ItChat#682]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:
Please press confirm on your phone.
Traceback (most recent call last):
  File "ItChat.py", line 30, in <module>
    itchat.auto_login(True)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/itchat/components/login.py", line 53, in login
    status = self.check_login()
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/itchat/components/login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/itchat/components/login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/usr/local/python2.7.15/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/local/python2.7.15/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/local/python2.7.15/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-54: ordinal not in range(128)
```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by baoyangc** [comment]
import sys
reload(sys)
sys.setdefaultencoding('utf8')

**Comment by catskytw** [comment]
Same here.
One day the whole program is disconnected and this error has occurred when relogin.

**Comment by bufeii** [comment]
在python3中也遇到过这情况
