### ISSUE TITLE
登陆问题 

### ISSUE THREAD

**Issue by Anning1007** [littlecodersh/ItChat#695]
```
itchat.auto_login()

itchat.send('Hello, filehelper', toUserName='filehelper')

itchat has already logged in.
itchat has already logged in.
Traceback (most recent call last):

  File "<ipython-input-38-4685c6ed2cab>", line 3, in <module>
    itchat.send('Hello, filehelper', toUserName='filehelper')

  File "D:\newpython\lib\itchat\components\messages.py", line 513, in send
    r = self.send_msg(msg, toUserName)

  File "D:\newpython\lib\itchat\components\messages.py", line 283, in send_msg
    r = self.send_raw_msg(1, msg, toUserName)

  File "D:\newpython\lib\itchat\components\messages.py", line 264, in send_raw_msg
    url = '%s/webwxsendmsg' % self.loginInfo['url']

KeyError: 'url'
```

您的itchat版本为：`1.3.10`

其他的内容或者问题更详细的描述都可以添加在下面：

> 显示已经登录 但是无法发送消息

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by FutureIsM** [comment]
+1未解决
