### ISSUE TITLE
登录几个小时候必然会报错退出提示LOG OUT!

### ISSUE THREAD

**Issue by AutoInfor** [littlecodersh/ItChat#710]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Python34\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Python34\lib\socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004AAD940>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python34\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1534051309500&sid=%2B6XGqcLFwx9jlwwb&_=1534051309500&skey=%40crypt_17037015_afa70a566341119ea42824a739a3deef&deviceid=e610994856711892&synckey=1_679411130%7C2_679429548%7C3_679429541%7C11_679422660%7C201_1534043703%7C1000_1534030098%7C1001_1534028234&uin=2528663440 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004AAD940>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\itchat\components\login.py", line 303, in sync_check
    r = self.s.get(url, params=params, headers=headers, timeout=config.TIMEOUT)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?r=1534051309500&sid=%2B6XGqcLFwx9jlwwb&_=1534051309500&skey=%40crypt_17037015_afa70a566341119ea42824a739a3deef&deviceid=e610994856711892&synckey=1_679411130%7C2_679429548%7C3_679429541%7C11_679422660%7C201_1534043703%7C1000_1534030098%7C1001_1534028234&uin=2528663440 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004AAD940>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\itchat\components\login.py", line 247, in maintain_loop
    i = sync_check(self)
  File "C:\Python34\lib\site-packages\itchat\components\login.py", line 306, in sync_check
    if not isinstance(e.args[0].args[1], BadStatusLine):
IndexError: tuple index out of range###

**Comment by ChenWang01** [comment]
How to solve this problem? I have the same issue.
