### ISSUE TITLE
ubuntu14.04下执行python2.7的itchat,登录成功了但是报错，请问这是什么问题

### ISSUE THREAD

**Issue by usersuccess** [littlecodersh/ItChat#737]
import itchat
from itchat.content import *
@itchat.msg_register(TEXT) #这里的TEXT表示如果有人发送文本消息，那么就会调用下面的方法
def simple_reply(msg):
#这个是向发送者发送消息
itchat.send_msg('已经收到了文本消息，消息内容为%s'%msg['Text'],toUserName=msg['FromUserName'])
return "T reveived: %s" % msg["Text"] #返回的给对方的消息，msg["Text"]表示消息的内容

Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/local/lib/python2.7/dist-packages/itchat/components/login.py", line 270, in maintain_loop
except requests.exceptions.ReadTimeout:
AttributeError: 'module' object has no attribute 'ReadTimeout'

Start auto replying.

**Comment by YoungNK** [comment]
+1

**Comment by usersuccess** [comment]
刚刚我去研究了一下，可能是requests的问题，然后sudo pip install requests  --upgrade把requests升级就可以了，之后变成了/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning，但是别人给我发的消息已经自动发给他了

**Comment by leon-xxn** [comment]
> > 刚刚我去研究了一下，可能是requests的问题，然后sudo pip install requests --upgrade把requests升级就可以了，之后变成了/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> > InsecurePlatformWarning，但是别人给我发的消息已经自动发给他了
> 
> 更新后我的问题依旧

你用的是python2.7还是python3

**Comment by Gengar-666** [comment]
同样的问题

**Comment by heye0507** [comment]
确实是requests版本太老的问题，升级requests库后问题就解决了
