### ISSUE TITLE
能导入itchat模块，用不了属性怎么搞

### ISSUE THREAD

**Issue by 95first** [littlecodersh/ItChat#808]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/WX_itchat/itchat.py", line 1, in <module>
    import itchat
  File "C:\Users\Administrator\Desktop\WX_itchat\itchat.py", line 2, in <module>
    itchat.run(debug=True)
AttributeError: partially initialized module 'itchat' has no attribute 'run' (most likely due to a circular import)

Process finished with exit code 1
[在这里粘贴完整日志]
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/WX_itchat/itchat.py", line 1, in <module>
    import itchat
  File "C:\Users\Administrator\Desktop\WX_itchat\itchat.py", line 2, in <module>
    itchat.auto_login()
AttributeError: partially initialized module 'itchat' has no attribute 'auto_login' (most likely due to a circular import)

Process finished with exit code 1

您的itchat版本为：`[1.3.10]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

导入itchat模块正常，用不了模块属性！

**Comment by Ujhhgtg** [comment]
把你自己的itchat.py（也就是C:/Users/Administrator/Desktop/WX_itchat/itchat.py）重命名一下
