### ISSUE TITLE
请教怎么解决证书问题Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.

### ISSUE THREAD

**Issue by qqizai** [littlecodersh/ItChat#810]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/itchat/utils.py", line 124, in test_connect
    r = requests.get(config.BASE_URL)
  File "/usr/local/python3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

You can't get access to internet or wechat domain, so exit.
```

您的itchat版本为：`[1.2.32]`。

其他的内容或者问题更详细的描述都可以添加在下面：

> [在阿里云服务器上面运行就出现异常，报的就是上面的错误，我也尝试安装2015.4.28的证书，但是无效，说我requests的证书2017.4.17的证书比2015的高级，是不是证书没有起效？请大佬帮忙看一下]

**Comment by ybsdegit** [comment]
同问
