### ISSUE TITLE
关于恢复消息撤回遇到问题

### ISSUE THREAD

**Issue by Floweryu** [littlecodersh/ItChat#823]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
{'MsgId': '5136685017736235886', 'FromUserName': '@516e6252640421b95714cf8c75830e4439ae78fb423eed5a0b62e0bc1e076618', 'ToUserName': '@@1905614933f9094a2245df5ccea5dfb8e74df3a0d06cdaf264c5d32710b64303', 'MsgType': 1, 'Content': 'GG嘎嘎嘎嘎那你呢', 'Status': 3, 'ImgStatus': 1, 'CreateTime': 1557061272, 'VoiceLength': 0, 'PlayLength': 0, 'FileName': '', 'FileSize': '', 'MediaId': '', 'Url': '', 'AppMsgType': 0, 'StatusNotifyCode': 0, 'StatusNotifyUserName': '', 'RecommendInfo': {'UserName': '', 'NickName': '', 'QQNum': 0, 'Province': '', 'City': '', 'Content': '', 'Signature': '', 'Alias': '', 'Scene': 0, 'VerifyFlag': 0, 'AttrStatus': 0, 'Sex': 0, 'Ticket': '', 'OpCode': 0}, 'ForwardFlag': 0, 'AppInfo': {'AppID': '', 'Type': 0}, 'HasProductId': 0, 'Ticket': '', 'ImgHeight': 0, 'ImgWidth': 0, 'SubMsgType': 0, 'NewMsgId': 5136685017736235886, 'OriContent': '', 'EncryFileName': '', 'Type': 'Text', 'Text': 'GG嘎嘎嘎嘎那你呢'}

Traceback (most recent call last):
  File "D:\Python3.7.2\lib\site-packages\itchat\components\register.py", line 66, in configured_reply
    r = replyFn(msg)
  File "D:/Learn_Python/Play_微信/message_view.py", line 87, in send_msg_helper
    old_msg_id = re.search("<msgid>(.*?)</msgid>", msg['Content']).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

您的itchat版本为：`1.2.32`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by Floweryu** [comment]
监听不到群消息，msg文件找不到actualUserName。
