### ISSUE TITLE
无法获取用户

### ISSUE THREAD

**Issue by weathon** [littlecodersh/ItChat#864]
我给自己发消息，获取了Username但是我想获取昵称失败了
请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
Start auto replying.
U
@5c15a165fd62f112a45ee79a9fcdfeef34d67ea2c328cc60d722c0b50707e898
Traceback (most recent call last):
  File "/home/wayne/.local/lib/python3.6/site-packages/itchat/components/register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "main.py", line 24, in text_reply
    author = itchat.search_friends(userName=msg.fromUserName)[0]
KeyError: 0

```

您的itchat版本为：`[在这里填写版本号]`。1.3.10
其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by weathon** [comment]
代码如下
```python

import itchat

userList=[]

@itchat.msg_register(itchat.content.TEXT,isFriendChat=False)
def text_reply(msg):
    print(msg.text)
    print(msg.fromUserName)
    author = itchat.search_friends(userName=msg.fromUserName)[0]
    author.send('greeting, littlecoder!')




itchat.auto_login(enableCmdQR=2,hotReload=True)
itchat.run(debug=True)```

**Comment by weathon** [comment]
看来是不用那个```[0]```，但是文档确实这么写的，希望改一下文档吧
https://itchat.readthedocs.io/zh/latest/

**Comment by weathon** [comment]
Never mind
