### ISSUE TITLE
如何屏蔽链接超时的错误输出？

### ISSUE THREAD

**Issue by TheThreeDog** [littlecodersh/ItChat#922]
我在Linux实现了一款控制台微信，为了交互功能，我把itchat.run放到了子线程中启动。主线程控制交互逻辑。但是现在发现itchat调用到的urllib3和request会偶尔报错链接超时，这个错误并不影响运行和使用，但是错误会全部输出到终端严重影响使用体验。

我想问是否有办法可以屏蔽掉这些Exception的输出。我尝试了直接在run的地方try Exception但是似乎捕获不到，子线程的错误输出仍然会输出到终端。

itchat版本：1.3.10

项目地址：
https://github.com/TheThreeDog/TouchFish/tree/master/WechatOfConsole

错误输出：
```
Traceback (most recent call last):
File "/home/threedog/.local/lib/python3.5/site-packages/urllib3/connection.py", line 157, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw
File "/home/threedog/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 84, in create_connection
raise err
File "/home/threedog/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 74, in create_connection sock.connect(sa)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/threedog/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 672, in urlopen
chunked=chunked,
File "/home/threedog/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 376, in _make_request
self._validate_conn(conn)
File "/home/threedog/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
conn.connect()
File "/home/threedog/.local/lib/python3.5/site-packages/urllib3/connection.py", line 334, in connect
conn = self._new_conn()
File "/home/threedog/.local/lib/python3.5/site-packages/urllib3/connection.py", line 164, in _new_conn % (self.host, self.timeout),
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbb7af79208>, 'Connection to webpush.wx.qq.com timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/home/threedog/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
 timeout=timeout
File "/home/threedog/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 720, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
File "/home/threedog/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 436, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?deviceid=e769112720069194&uin=2799259404&sid=Flc2czqXb9RZXSry&_=1592019662309&r=1592019662309&synckey=1_711829443%7C2_711829680%7C3_711829389%7C11_711829469%7C19_704%7C201_1592019555%7C203_1592014136%7C206_1%7C1000_1592005044%7C1001_1592005047&skey=%40crypt_126596ce_d1f3f6e9b9288dabbc33c19007787c93 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbb7af79208>, 'Connection to webpush.wx.qq.com timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/threedog/.local/lib/python3.5/site-packages/itchat/components/login.py", line 303, in sync_check r = self.s.get(url, params=params, headers=headers, timeout=config.TIMEOUT)
File "/home/threedog/.local/lib/python3.5/site-packages/requests/sessions.py", line 546, in get return self.request('GET', url, **kwargs)
File "/home/threedog/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request  resp = self.send(prep, **send_kwargs)
File "/home/threedog/.local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send r = adapter.send(request, **kwargs)
File "/home/threedog/.local/lib/python3.5/site-packages/requests/adapters.py", line 504, in send raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='webpush.wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?deviceid=e769112720069194&uin=2799259404&sid=Flc2czqXb9RZXSry&_=1592019662309&r=1592019662309&synckey=1_711829443%7C2_711829680%7C3_711829389%7C11_711829469%7C19_704%7C201_1592019555%7C203_1592014136%7C206_1%7C1000_1592005044%7C1001_1592005047&skey=%40crypt_126596ce_d1f3f6e9b9288dabbc33c19007787c93 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbb7af79208>, 'Connection to webpush.wx.qq.com timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/threedog/.local/lib/python3.5/site-packages/itchat/components/login.py", line 247, in maintain_loop i = sync_check(self)
File "/home/threedog/.local/lib/python3.5/site-packages/itchat/components/login.py", line 306, in sync_check
if not isinstance(e.args[0].args[1], BadStatusLine):
IndexError: tuple index out of range
```

**Comment by vvanglro** [comment]
+1

**Comment by hansenma** [comment]
+1
