### ISSUE TITLE
解决无法页面登陆微信的问题

### ISSUE THREAD

**Issue by gitgzz** [littlecodersh/ItChat#943]
在二十一世纪微信页面只有老微信才可以登陆微信网页版，为了解决此问题，需安装一个插件来解决
这个插件叫做 itchat-uos 

**pip install itchat-uos**  #安装后即可登陆微信，python3用pip3安装

项目地址：https://github.com/why2lyj/ItChat-UOS

友情提示登陆二维码显示不出来可以用 itchat.auto_login(enableCmdQR=2) 展现二维码

**Comment by haydenzhourepo** [comment]
@gitgzz  可行

**Comment by haydenzhourepo** [comment]
@gitgzz  使用 docker 打包后 运行 扫描不行

**Comment by haydenzhourepo** [comment]
这是dockerfile
FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "flask", "run"]

**Comment by Hailaylin** [comment]
我的是老账户可以用，新注册的账户登录报错，不知道为什么
````Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Traceback (most recent call last):
  File ".\bot.py", line 7, in <module>
    itchat.auto_login()
  File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 55, in login
    status = self.check_login()
  File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 141, in check_login
    if process_login_info(self, r.text):
  File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 183, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

**Comment by Hailaylin** [comment]
> 我的是老账户可以用，新注册的账户登录报错，不知道为什么
> 
> ```
> Downloading QR code.
> Please scan the QR code to log in.
> Please press confirm on your phone.
> Traceback (most recent call last):
>   File ".\bot.py", line 7, in <module>
>     itchat.auto_login()
>   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\register.py", line 35, in auto_login
>     self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
>   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 55, in login
>     status = self.check_login()
>   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 141, in check_login
>     if process_login_info(self, r.text):
>   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 183, in process_login_info
>     core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
> KeyError: 'wxsid'
> ```

已解决，新用户不能用，老用户可 uos的针不戳！

**Comment by j796160836** [comment]
我也遇到 docker 打包後無法掃瞄正常執行的問題

我用另外一個套件就解決了，Dockerfile 如下
https://github.com/littlecodersh/ItChat/issues/939#issuecomment-914691384

**Comment by dwaynewei** [comment]
* 同样老用户可以登陆了。 感谢！！
* 只是，还想单独用一个微信来做这个登陆使用。 目前老的微信也很难搞到了。 要是什么时候微信新用户也可以登陆就完美了。

**Comment by FancyYan123** [comment]
同求新用户可以登录就好了，新注册的小号用不上有点尴尬

**Comment by RobotWizard916** [comment]
新注册小号用不了，是微信把相关键值改了吗？多老的账户可以用不知道？

**Comment by MikeChen012345** [comment]
> 我的是老账户可以用，新注册的账户登录报错，不知道为什么
> 
> ```
> Downloading QR code.
> Please scan the QR code to log in.
> Please press confirm on your phone.
> Traceback (most recent call last):
>   File ".\bot.py", line 7, in <module>
>     itchat.auto_login()
>   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\register.py", line 35, in auto_login
>     self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
>   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 55, in login
>     status = self.check_login()
>   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 141, in check_login
>     if process_login_info(self, r.text):
>   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 183, in process_login_info
>     core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
> KeyError: 'wxsid'
> ```

老哥解决了吗，我前几天可以用今天突然就报wxsid的错误了

**Comment by bydreamxxx** [comment]
> > 我的是老账户可以用，新注册的账户登录报错，不知道为什么
> > ```
> > Downloading QR code.
> > Please scan the QR code to log in.
> > Please press confirm on your phone.
> > Traceback (most recent call last):
> >   File ".\bot.py", line 7, in <module>
> >     itchat.auto_login()
> >   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\register.py", line 35, in auto_login
> >     self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
> >   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 55, in login
> >     status = self.check_login()
> >   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 141, in check_login
> >     if process_login_info(self, r.text):
> >   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 183, in process_login_info
> >     core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
> > KeyError: 'wxsid'
> > ```
> 
> 老哥解决了吗，我前几天可以用今天突然就报wxsid的错误了

一样的 老用户也不行了

**Comment by MikeChen012345** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by shirubei** [comment]
老用户，一直在用，前几天登录都没问题。今天重新登录也报错KeyError: 'wxsid'， 跟上面老哥的一模一样。

**Comment by Sean16SYSU** [comment]
同样是wxsid的问题，有什么推荐的解决方案吗

**Comment by ArmCommunity** [comment]
刚刚退出后，再登录，也是上述的报错

**Comment by shirubei** [comment]
怀疑是微信改了接口参数什么的。
据说统信UOS版的微信最近更新了，怀疑是不是跟这个接口参数修改有关？期待有高手对这个抓包看看能不能再弄出一个解决方案来。

**Comment by itachilee** [comment]
> > 我的是老账户可以用，新注册的账户登录报错，不知道为什么
> > ```
> > Downloading QR code.
> > Please scan the QR code to log in.
> > Please press confirm on your phone.
> > Traceback (most recent call last):
> >   File ".\bot.py", line 7, in <module>
> >     itchat.auto_login()
> >   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\register.py", line 35, in auto_login
> >     self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
> >   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 55, in login
> >     status = self.check_login()
> >   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 141, in check_login
> >     if process_login_info(self, r.text):
> >   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 183, in process_login_info
> >     core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
> > KeyError: 'wxsid'
> > ```
> 
> 已解决，新用户不能用，老用户可 uos的针不戳！

老账号也不可以用，身边朋友的账号试过了都不行

**Comment by MikeChen012345** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by HuiGitH** [comment]
> > 我的是老账户可以用，新注册的账户登录报错，不知道为什么
> > ```
> > Downloading QR code.
> > Please scan the QR code to log in.
> > Please press confirm on your phone.
> > Traceback (most recent call last):
> >   File ".\bot.py", line 7, in <module>
> >     itchat.auto_login()
> >   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\register.py", line 35, in auto_login
> >     self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
> >   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 55, in login
> >     status = self.check_login()
> >   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 141, in check_login
> >     if process_login_info(self, r.text):
> >   File "C:\Users\78429\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 183, in process_login_info
> >     core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
> > KeyError: 'wxsid'
> > ```
> 
> 已解决，新用户不能用，老用户可 uos的针不戳！

请问这步当时是怎么解决的？谢谢！

**Comment by MikeChen012345** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by shirubei** [comment]
UOS版的已经不行了。找到一个代替方案：用windows版wechat hook，然后就可以跑了。

**Comment by Mr-KID-github** [comment]
> UOS版的已经不行了。找到一个代替方案：用windows版wechat hook，然后就可以跑了。

咋用呀老铁

**Comment by MikeChen012345** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by shirubei** [comment]
> > UOS版的已经不行了。找到一个代替方案：用windows版wechat hook，然后就可以跑了。
> 
> 咋用呀老铁

去这个账号cixingguangming55555的github看wechat-bot 这个库
