### ISSUE TITLE
hotReload为True的情况下，登录的时候报错 

### ISSUE THREAD

**Issue by hifeiwenchao** [littlecodersh/ItChat#946]
Traceback (most recent call last):
  File "/opt/app/new/leisu_api/build/test.py", line 188, in <module>
    start_wx()
  File "/opt/app/new/leisu_api/build/test.py", line 182, in start_wx
    itchat.auto_login(hotReload=True)
  File "/root/miniconda3/envs/leisu_api/lib/python3.7/site-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/root/miniconda3/envs/leisu_api/lib/python3.7/site-packages/itchat/components/login.py", line 55, in login
    status = self.check_login()
  File "/root/miniconda3/envs/leisu_api/lib/python3.7/site-packages/itchat/components/login.py", line 141, in check_login
    if process_login_info(self, r.text):
  File "/root/miniconda3/envs/leisu_api/lib/python3.7/site-packages/itchat/components/login.py", line 183, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

**Comment by zishang33** [comment]
I have the same problem, have you solved it?

**Comment by QYQSDTC** [comment]
Same problem

**Comment by niucang** [comment]
Same problem

**Comment by iCodey** [comment]
Same problem
