### ISSUE TITLE
itchat.auto_login登录问题

### ISSUE THREAD

**Issue by 252258606** [littlecodersh/ItChat#970]
> 最近遇到一个问题，我需要用到itchat群发一个信息，但最近调用itchat.auto_login()时，微信扫码登录会延迟5秒，就这这个时间内会重新产生登录的二维码，登录不成功，发送不了信息

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by LX162** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 1ighttack** [comment]
我也存在这样的问题，希望得到解决

**Comment by Medesol** [comment]
同样的问题

**Comment by heart5** [comment]
同样的问题也发生了。是一个非常用微信号。

**Comment by LX162** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhaohuiwei1990** [comment]
您好，我已收到您的邮件，会尽快回复！

**Comment by lindalinya** [comment]
建议给login加一个延时reloading二维码的时间长度参数

**Comment by zhayujie** [comment]
我现在临时方案是在 itchat/components/login.py 的 login() 函数中，在进入 while not isLoggedIn 循环前加了一个sleep

<img width="778" alt="image" src="https://user-images.githubusercontent.com/26161723/208282510-188997cb-2f3f-490b-97fe-fef713193949.png">

期待能更新版本

**Comment by rankang666** [comment]
修改判断uuid代码可以解决问题
<img width="487" alt="itchat_bug" src="https://user-images.githubusercontent.com/43208859/211954284-f2e7d9cb-535e-494e-9c97-98a1f16b02fe.png">

**Comment by Stevendu666** [comment]
██████████████████  ████    ████  ██  ██████  ██████  ████  ██████        ██���█
██              ██          ██  ████    ████████  ████████  ██  ██      ██  ██
██  ██████████  ██████  ████      ██████████  ████      ██  ██████    ██  ████
██  ██      ██  ██  ██  ████    ██      ██████████  ████            ████  ████
██  ██      ██  ██  ██        ██████      ██████████        ██  ████  ████████
██  ██      ██  ████  ████      ██    ██  ████  ██  ██  ██  ████            ██
██  ██████████  ██████    ████████████  ██  ██  ██████  ██████  ██  ██      ██
██              ████  ██  ██  ████    ██  ████████  ██████  ██  ████  ████  ██
██████████████████████████████████████████████████████████████████████████████
Please scan the QR code to log in.




Please press confirm on your phone.
Log in time out, reloading QR code.
Log in time out, reloading QR code.
Log in time out, reloading QR code.
Log in time out, reloading QR code.
[ERROR][2023-02-21 11:37:38][app.py:19] - App startup failed!
[ERROR][2023-02-21 11:37:38][app.py:20] - list index out of range
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    channel.startup()
  File "/home/lighthouse/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup
    itchat.auto_login(enableCmdQR=2)
  File "/usr/local/lib/python3.6/site-packages/itchat/components/register.py", line 36, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 61, in login
    status = self.check_login()
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 152, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 197, in process_login_info
    skey = re.findall('<skey>(.*?)</skey>', r.text, re.S)[0]
IndexError: list index out of range

不行啊 大佬看一下

**Comment by rankang666** [comment]
![image](https://user-images.githubusercontent.com/43208859/220274656-de174720-1c39-4a90-aa75-78ac534b880a.png)
调整为这样

**Comment by jianghongping** [comment]
也不行啊，一直重复显示 please scan the QR code to log in

**Comment by YYJ39831** [comment]
我修改之后，扫码成功了，但是提示 Traceback (most recent call last)

**Comment by gavin2021** [comment]
在utils.py  def test_connect(retryTime=10): 将retryTime =5 改为10 可以避免扫描后再次出现二维码。

**Comment by wsyslf1996** [comment]
> ██████████████████ ████ ████ ██ ██████ ██████ ████ ██████ ██���█ ██ ██ ██ ████ ████████ ████████ ██ ██ ██ ██ ██ ██████████ ██████ ████ ██████████ ████ ██ ██████ ██ ████ ██ ██ ██ ██ ██ ████ ██ ██████████ ████ ████ ████ ██ ██ ██ ██ ██ ██████ ██████████ ██ ████ ████████ ██ ██ ██ ████ ████ ██ ██ ████ ██ ██ ██ ████ ██ ██ ██████████ ██████ ████████████ ██ ██ ██████ ██████ ██ ██ ██ ██ ████ ██ ██ ████ ██ ████████ ██████ ██ ████ ████ ██ ██████████████████████████████████████████████████████████████████████████████ Please scan the QR code to log in.
> 
> Please press confirm on your phone. Log in time out, reloading QR code. Log in time out, reloading QR code. Log in time out, reloading QR code. Log in time out, reloading QR code. [ERROR][2023-02-21 11:37:38][app.py:19] - App startup failed! [ERROR][2023-02-21 11:37:38][app.py:20] - list index out of range Traceback (most recent call last): File "app.py", line 17, in channel.startup() File "/home/lighthouse/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 37, in startup itchat.auto_login(enableCmdQR=2) File "/usr/local/lib/python3.6/site-packages/itchat/components/register.py", line 36, in auto_login loginCallback=loginCallback, exitCallback=exitCallback) File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 61, in login status = self.check_login() File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 152, in check_login if process_login_info(self, r.text): File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 197, in process_login_info skey = re.findall('(.*?)', r.text, re.S)[0] IndexError: list index out of range
> 
> 不行啊 大佬看一下

根据我调试发现，出现问题的原因是登录的微信号没有开通微信支付。去开通一下就可以了。

**Comment by lhyyzh** [comment]
> 我现在临时方案是在 itchat/components/login.py 的 login() 函数中，在进入 while not isLoggedIn 循环前加了一个sleep
> 
> <img alt="image" width="778" src="https://user-images.githubusercontent.com/26161723/208282510-188997cb-2f3f-490b-97fe-fef713193949.png">
> 
> 期待能更新版本

这个方法试了一下，好像可以扫码、确认成功。但马上在auto_login()位置报错“keyError：‘’wxsid”
![微信图片_20230831180309](https://github.com/littlecodersh/ItChat/assets/7620958/acd1724b-4e9e-486e-a8b8-657b80c78add)

**Comment by AFUL1991** [comment]
一方面是微信需要实名认证，不然会有报错找不到wxsid；（这个能不能改返回的数据绕过我不知道，没试，我直接实名认证了）
一方面是需要改一下源码，不然5秒后自动刷新了二维码，前面网友给了改的办法。
这两条缺一不可。
