### ISSUE TITLE
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by shishirui** [littlecodersh/ItChat#98]
我的一个程序，是利用itchat来不断发消息的。每次开始后，大约经过几十分钟后，就会出现如下错误：

```
Unhandled exception in thread started by <function do at 0x10e84b140>
Traceback (most recent call last):
  File "./test.py", line 90, in do
    sendIMEI(currentIMEI, mpUserName)
  File "./test.py", line 54, in sendIMEI
    itchat.send(msg=text.decode("utf-8"), toUserName=UserName)
  File "/Library/Python/2.7/site-packages/itchat/__init__.py", line 67, in send
    return __client.send_msg(msg, toUserName)
  File "/Library/Python/2.7/site-packages/itchat/client.py", line 445, in send_msg
    r = self.s.post(url, data = json.dumps(payloads, ensure_ascii = False).encode('utf8'), headers = headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:590)
```

不知道是什么原因呢？

**Comment by littlecodersh** [comment]
@shishirui 这是ssl的问题。
你的python版本是多少？版本过低可能出现这个问题。
如果版本没有问题，可以在send语录外面catch这个exception。

**Comment by shishirui** [comment]
@littlecodersh 我用的是Python 2.7.10，我这就加上catch试试。

**Comment by shishirui** [comment]
已经好了，谢谢。
