### ISSUE TITLE
我在登录后出现'xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4' 怎么解决

### ISSUE THREAD

**Issue by jiaochanghaoserverss** [littlecodersh/ItChat#995]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by river7816** [comment]
> 在提交前，请确保您已经检查了以下内容!
> 
> * [x]  您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
> * [x]  我已经阅读并按[文档](http://itchat.readthedocs.io/zh/latest/) 中的指引进行了操作
> * [x]  您的问题没有在[issues](https://github.com/littlecodersh/itchat/issues)报告，否则请在原有issue下报告
> * [x]  本问题确实关于`itchat`, 而不是其他项目.
> * [x]  如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp](https://github.com/littlecodersh/itchatmp)项目
> 
> 请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:
> 
> ```
> [在这里粘贴完整日志]
> ```
> 
> 您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）
> 
> 其他的内容或者问题更详细的描述都可以添加在下面：
> 
> > [您的内容]

我也遇到了相同问题，itchat 版本`1.3.10`
```
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Traceback (most recent call last):
  File "/Users/river/Desktop/telegram/test.py", line 3, in <module>
    itchat.auto_login()
  File "/Users/river/miniforge3/envs/nlp/lib/python3.10/site-packages/itchat/components/register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/Users/river/miniforge3/envs/nlp/lib/python3.10/site-packages/itchat/components/login.py", line 53, in login
    status = self.check_login()
  File "/Users/river/miniforge3/envs/nlp/lib/python3.10/site-packages/itchat/components/login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "/Users/river/miniforge3/envs/nlp/lib/python3.10/site-packages/itchat/components/login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/Users/river/miniforge3/envs/nlp/lib/python3.10/xml/dom/minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
  File "/Users/river/miniforge3/envs/nlp/lib/python3.10/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/Users/river/miniforge3/envs/nlp/lib/python3.10/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 64, column 4
```
以下是我的代码
```python
import itchat

itchat.auto_login()
itchat.send('Hello, filehelper', toUserName='filehelper')
```

**Comment by LX162** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lxdhhy** [comment]
谢谢，您的邮件已收到,我会尽快给回复！

**Comment by zhaohuiwei1990** [comment]
您好，我已收到您的邮件，会尽快回复！

**Comment by jouhpf** [comment]
我也遇到了类似的问题，请问解决了吗

**Comment by river7816** [comment]
> 我也遇到了类似的问题，请问解决了吗

并没有

**Comment by smallXueTu** [comment]
![image](https://github.com/littlecodersh/ItChat/assets/36348070/487131fb-1116-4c3e-aa48-280b4083a3ac)
有些账号已经不能用网页版了，换个账号即可

**Comment by TLovers** [comment]
我15年的号都无法登陆了

**Comment by sheiy** [comment]
擦 我的号也不行

**Comment by qs-lll** [comment]
我15年的号也不行
